<?php
/**
 * OntoWiki about template
 */

?>
<?php foreach ($this->data as $name => $section): ?>
<h2 class="clearfloat"><?php echo $name ?></h2>
    <table class="separated-vertical">
        <?php foreach ($section as $name => $value): ?>
            <tr>
                <td width="35%"><?php echo $name ?></td>
                <td><?php echo $value ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endforeach; ?>

