<?php
//$p_name = $this->p_name;
//$dirs = $this->dirs;
//$files = $this->files;
//$extension_url = $this->extension_url;

//echo "<br/> p_name: $p_name <br/> dirs: $dirs <br/> files: $files <br/> extension_url: $extension_url <br/>";
echo "<h3 style=\"color:#FF0000\">Do you want to uninstall this extension before the reinstall right now? </h3>";
echo<<<choice
	<div><button type="button" onclick="window.location.href='$this->reinstall'"> YES</button> <button type="button" onclick="window.location.href='$this->notreinstall'"> NO </button>	</div>
choice;

?>

