<li class="has-contextmenu-area foaf-person <?php if ($this->odd) {echo "odd";} else {echo "even";} ?>">
 <span class="pic">
        <?php 
        $picUrl = "http://www.jsmemladi.cz/wp-content/uploads/facebook_no_profile_pic2.gif";
        if (isset($this->instanceData['img'])){
            $picUrl = $this->instanceData['img'][0]['uri'];
        } else if (isset($this->instanceData['depiction'])){
            $picUrl = $this->instanceData['depiction'][0]['uri'];
        }
        ?>
        <img class="avatar" src="<?php echo $picUrl; ?>"  style="max-width:60px"/>

    </span>
    <span class="name">
        <?php 
        $name = "";
        if (isset($this->instanceData['name'])){
            $name = $this->instanceData['name'][0]['uri']; 
        } else {
            if (isset($this->instanceData['firstname'])){
                $name = $this->instanceData['firstname'][0]['value']; 
            }
            if (isset($this->instanceData['surname'])){
                $name .= $this->instanceData['surname'][0]['value']; 
            } else if (isset($this->instanceData['familyName'])){
                $name .= $this->instanceData['familyName'][0]['value']; 
            } else if (isset($this->instanceData['family_name'])){
                $name .= $this->instanceData['family_name'][0]['value']; 
            }
        } 
        if (isset($this->instanceData['nick']) && $this->instanceData['nick'][0]['value'] != $name){
            if($name == ""){
                $name = $this->instanceData['nick'][0]['value']; 
            } else {
                $name .= ' ('.$this->instanceData['nick'][0]['value'].')'; 
            }
        } 
        echo $name;
        ?>
    </span>
<div class="contextmenu">
    <a class="item rdfauthor-edit-property" onclick="dssnNetworkOptions(event);">
        <span class="icon icon-edit" title="Options"><span>Options</span></span>
    </a>
</div>

</li>
