<?php $item = $this->activity ?>
<li class="has-contextmenu-area dssn-activity <?php if ($this->odd) {echo "odd";} else {echo "even";} ?>">
    <span class="subject">
        <a href="<?php echo $item['actorUri'] ?>">
            <img class="avatar" src="<?php echo $item['actorAvatar'] ?>" />
            <?php echo $item['actorLabel'] ?>
        </a>
    </span>
    <span class="verb">
        <?php echo $item['verbLabel'] ?> 
        <a href="<?php echo $item['objectUri'] ?>"><?php echo $item['objectTypeLabel'] ?></a>
    </span>
    <span title="<?php echo $item['published'] ?>" class="published"><?php echo $item['publishedLabel'] ?></span>:
    <span class="object">
        <a href="<?php echo $item['objectUri'] ?>"><?php echo $item['objectUri'] ?></a>
        <?php if(isset($item['objectThumbnail'])) :?>
        <a href="<?php echo $item['objectUri'] ?>">
            <img class="thumbnail" src="<?php echo $item['objectThumbnail'] ?>" />
        </a>
        <?php endif; ?>
        <?php if(isset($item['objectContent'])) :?>
        <span class="content"><?php echo $item['objectContent'] ?></span>
        <?php endif; ?>
    </span>
<div class="contextmenu">
    <a class="item rdfauthor-edit-property" onclick="dssnActivityOptions(event);">
        <span class="icon icon-edit" title="Options"><span>Options</span></span>
    </a>
</div>

</li>
