<?php if(count($this->instanceInfo) == 0) { ?>
<p class="messagebox info">no persons found. add one via the box to the right.</p>
<?php } else { 
    ?>
<ol class="bullets-none separated">
<?php
$i=1; $odd = true;
foreach ($this->instanceInfo as $instance){
    echo $this->partial('partials/list_dssn_network_item.phtml',
        array(
            'odd'          => $odd,
            'i'            => $i,
            'instanceInfo' => $this->instanceInfo,
            'instance'     => $instance,
            'instanceData' => $this->instanceData[$instance['uri']]
        )
    );
    $odd = !$odd;
    $i++;
} ?>
</ol>
<?php } ?>