<?php if(count($this->instanceInfo) == 0) { ?>
<p class="messagebox info">no recent activities found</p>
<?php } else { ?>
<ol class="bullets-none separated">
<?php
$i=1; $odd = true;
foreach ($this->instanceInfo as $instance){
    $factory = new DSSN_Activity_Factory(OntoWiki::getInstance());
    $activity = $factory->getFromStore($instance['uri']);
    // should we use different templates for different activity types here?
    echo $this->partial('partials/list_dssn_activities_item.phtml',
        array(
            'odd'          => $odd,
            'i'            => $i,
            'instanceInfo' => $this->instanceInfo,
            'activity'     => $activity
        )
    );
    $odd = !$odd;
    $i++;
} ?>
</ol>
<?php } ?>

