<script type="text/javascript">
    var actionURL = '<?php echo $this->actionUrl; ?>';
    var salt = '<?php echo $this->salt; ?>';
    <?php if( isset($this->modelUri) ){ echo "var graphURI = '".$this->modelUri."';"; }  ?>
    csvConfigs = [];
    <?php
    if( isset($this->configs) ){
        for($i = 0; $i < count($this->configs); $i++ ){
            echo "csvConfigs[".$i."] = '".wordwrap($this->configs[$i], 1024, "'\n+ '")."';\n";
        };
    }?>
</script>
<?php if( isset($this->scovo) ): ?>
<div><?php echo $this->_('Base URI:') ?><input type="text" id="uribase" value="initme" style="width:80%;"></div>
<div><?php echo $this->_('Data Range:') ?><span id="csvimportDatarange"></span></div>
<div><?php echo $this->_('Attributes:') ?>
<table id="csvimport-attributes">
    <tr>
        <th><?php echo $this->_('Attribute Name') ?></th>
    </tr>
</table>
</div>
<div><?php echo $this->_('Dimensions:') ?>

<table id="csvimport-dimensions">
    <tr>
        <th><?php echo $this->_('Dimension Name') ?></th>
    </tr>
</table>
</div>
<?php endif; ?>
<div style="position: relative; overflow: auto; width: 100%; height: 100%;" id="table-holder">
<?php echo $this->table ?>
</div>
