#!/bin/sh -e
# postinst script for ontowiki
#
# see: dh_installdeb(1)

echo "---- starting postinst $@"

mysql_run="mysql --defaults-extra-file=/etc/mysql/debian.cnf"

ow_user="ontowiki_deb"
ow_db="$ow_user"
ow_pass=`pwgen -1`
ow_pass="usepwgenhere"

#service mysql start
echo "create ontowiki user"
echo "CREATE USER '$ow_user'@'localhost' IDENTIFIED BY  '$ow_pass';" | $mysql_run || echo "user $ow_user already exist"

echo "grant usage for ontowiki user"
echo "GRANT USAGE ON * . * TO  '$ow_user'@'localhost' IDENTIFIED BY  '$ow_pass' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;" | $mysql_run

echo "create database"
echo "CREATE DATABASE IF NOT EXISTS  $ow_db ;" | $mysql_run

echo "grant privileges to ontowiki user"
echo "GRANT ALL PRIVILEGES ON $ow_db . * TO '$ow_user'@'localhost';" | $mysql_run

echo "flush privileges"
echo "FLUSH PRIVILEGES ;" | $mysql_run

chown www-data:www-data /var/log/ontowiki
chown www-data:www-data /var/cache/ontowiki
chown www-data:www-data /etc/ontowiki/config.ini
chmod 600 /etc/ontowiki/config.ini

a2enmod rewrite
a2enmod env
service apache2 restart

#DEBHELPER#

echo "---- ending postinst $@"
