<?php
// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
        );
?>

<?php if ($content = trim($this->partial( 'lod2/content.phtml', $templateData))): ?>
    
<div class="maincontent">
    <div class="section">
        <h3><?php echo $this->title ?></h3>
        <div class="section-content">
            <?php echo $content; ?>
        </div>
    </div>
</div>

<?php endif; ?>


