<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xml:lang="en"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <style type="text/css" media="all">
        @import "<?php echo $this->baseUri ?>css/main.css";
    </style>
    <title>Towards a LOD2 site</title>
</head>

<body>
<h1 property="dc:title">Towards a LOD2 site</h1>
<h2><?php echo $this->resourceUri ?> (selected resource)</h2>

<p class="author" rel="dc:creator">
  <span about="http://sebastian.tramp.name" typeof="foaf:Person">
    <span property="foaf:name">Sebastian Tramp</span> ● AKSW<br />
  </span>
  <span about="http://feedface.de/foaf/me" typeof="foaf:Person">
    <span property="foaf:name">Norman Heino</span> ● AKSW<br />
  </span>
  <span about="http://www.3feed.de/rdf/foaf.rdf/me" typeof="foaf:Person">
    <span property="foaf:name">Jonas Brekle</span> ● AKSW<br />
  </span>
</p>

<p class="abstract" property="dc:abstract">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus faucibus ligula a nulla tincidunt hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec dui eget odio venenatis pharetra nec ac erat. Proin ut libero ut diam condimentum pharetra id vel enim. Suspendisse fringilla ullamcorper nunc, id sollicitudin purus blandit et. Quisque pretium neque quis metus ultricies convallis. Donec a rutrum metus. Integer varius pharetra elit, ut tincidunt elit sodales non. Ut varius ante in libero imperdiet a euismod diam tincidunt. Fusce id ligula neque, vel sollicitudin leo. Proin semper lobortis diam, et facilisis tellus egestas in. Sed eu. </p>

<ul>
    <li><del>Norm: Linked Data URIs auf den site controller forwarden?</del></li>
        SiteHelper reagiert auf Event <code>onShouldLinkedDataRedirect</code>, setzt neuen
         Controller/Action und gibt <code>false</code> (= should not redirect) zurück.
    <li><del>Wie wird die Startseite erreichbar (also eigentlich das OW basedir)</del>
        <pre>
<del>index.default.controller = "site"
index.default.action = "lod2"</del>
        </pre>
        SiteHelper reagiert auf Event <code>onPostBootstrap</code> und injiziert SiteController und aktuell aktive
        Site als Standard-Route in den Router.
    </li>
    <li><del>Seebi: Test Modell</del></li>
    <li><del>Jonas: private Config für site modell</del>
test private config:<?php
foreach($this->privateConfig as $key => $value){
    echo " ".$key."=".$value;
}
?></li>
    <li>Seebi: Wie werden die Templates pro Klasse benutzt</li>
    <li>Welche view-variablen sind notwendig (mal bei Wordpress schauen)</li>
    <li>Norm: CBD + titles der selected resource über ressource klasse</li>
    <li>Norm: SPARQL API Methode + Listen methode?</li>
    <li>Norm: titles über TitleHelper aller in der CBD enthaltenen ressource?</li>
    <li>Wie werden zusatz-libs (php) eingebunden (z.B. für feeds)</li>
        <pre>
require_once ... normal
        </pre>
    <li><del>Norm: Wie wird modul-content gerendert (eigener context)</del></li>
        <pre>
echo $this->module('ttt', array('noChrome' => true)); // ein bestimtes Modul oder
echo $this->modules('sites.lod2', array('noChrome' => true)); // alle Module für Context 'sites.lod2'
        </pre>
        Beispiel: <?php echo $this->modules('sites.lod2', array('noChrome' => true)) ?>
        TODO: Was ist mit Titel, Menüs, Modulen mit Tabbed Content?
    <li><del>Jonas: Wie werden Bilder aus dem CSS referenziert</del></li>
        <pre>
bitte testen
        </pre>
    <li>...</li>
</ul>

<ul>Später:
    <li>Wie wird der URI helper zur Verfügung gestellt</li>
    <li>Wie werden Dokumente (z.B. PDFs) benutzt (über files component)</li>
</ul>

Navigation: <pre><?php var_dump($this->navi); ?></pre>

</body>
</html>