<?php
    if (isset($this->description[$this->resourceUri]['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'])) {
        $types = array ();
        foreach ($this->description[$this->resourceUri]['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'] as $property) {
            if ((isset($property['value'])) && (Erfurt_Uri::check($property['value']))) {
                $types[$property['value']] = true;
            }
        }
        switch ($types) {
            case (isset($types['http://usefulinc.com/ns/doap#Project'])):
                echo $this->partial( 'lod2/project.phtml', $templateData);
                break;
            case (isset($types['http://xmlns.com/foaf/0.1/Organization'])):
                echo $this->partial( 'lod2/partner.phtml', $templateData);
                break;
            default:
                break;
        }
    }
?>
