<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <div class="partner article first">
            <p class="meta">Properties of <?php echo $this->title ?>:
                <?php foreach ($this->description as $property => $propertyDescription): ?>
                    <?php echo $this->helper->getTitle($property) ?>
                <?php endforeach; ?>
            </p>

            <?php if (isset($this->description['http://rdfs.org/sioc/ns#content'])) : ?>
                <?php echo $this->description['http://rdfs.org/sioc/ns#content'][0]['value']; ?>
            <?php endif ?>

        </div>
    </div>
</div>
