<div class="section">
<?php

$querUri          = 'http://lod2.eu/Query/Testimonials';
$queryInstance    = new OntoWiki_Resource($querUri, OntoWiki::getInstance()->selectedModel);
$queryDescription = $queryInstance->getDescription();
$queryDescription = $queryDescription[$querUri];

$content = '';
if (isset($queryDescription['http://ns.ontowiki.net/SysOnt/sparql_code'][0]['value'])) {
    $sparqlCode = $queryDescription['http://ns.ontowiki.net/SysOnt/sparql_code'][0]['value'];
    $content    = $this->querylist($sparqlCode, 'lod2/item.phtml', array('options' => array('show_link' => true)));
}

$title = $queryInstance->getTitle();
if (empty($title)) {
    $title = 'Query Result';
}
?>
<div class="section random-results">
    <script type="text/javascript">
    $(document).ready(function () {
        var number  = $('.random-results').children('.section-content').length;
        var current = Math.floor(Math.random() * (number - 1));
        var maxHeight = 0;
        $('.random-results').children('.section-content').each(function (index) {
            if ($(this).height() > maxHeight) {
                maxHeight = $(this).height();
            }
            
            if (index !== current) {
                $(this).hide();
            }
        });
        // HACK: height seems to be not enough
        maxHeight += 20;
        $('.random-results .section-content').height(maxHeight);
        
        window.setInterval(function () {
            var next = (current + 1) % number;
            $('.random-results .section-content').eq(current).fadeOut(function () {
                $('.random-results .section-content').eq(next).fadeIn(function () {
                    current = next;
                });
            });
        }, 15000);
    });
    </script>
    <h3><?php echo $title ?></h3>
    <?php echo $content; ?>
</div>

