<?php

/**
 * OntoWiki modellist entry list template
 */
$odd = true;
?>

<?php if(!empty($this->prerendered)): ?>
    <?php print $this->prerendered; ?>
<?php elseif (!empty($this->entries)): ?>
    <ol class="bullets-none separated has-contextmenus-block">
        <?php foreach ($this->entries as $modelDetails): ?>
            <li>
                <a class="Model <?php echo $modelDetails['selected'] ?>" href="<?php echo $modelDetails['url'] ?>" about="<?php echo $modelDetails['graphUri'] ?>">
                    <?php echo $modelDetails['label'] ?>
                </a>
            </li>
        <?php endforeach; ?>
    </ol>
    <?php if ($this->showMeMore) :?>
        <a class="minibutton" style="display: inline-block;" id="modellist-more"><span class="icon icon-arrow-down"></span> Show Me More</a>
    <?php endif; ?>
<?php else: ?>
    <p class="messagebox info"><?php echo $this->_('No knowledge bases found.') ?></p>
<?php endif; ?>
