<?php

/**
 * OntoWiki model list template
 */

?>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Knowledge base <b class="caret"></b></a>
    <ul class="dropdown-menu">
        <?php if (!empty($this->data['models'])): ?>
            <?php foreach ($this->data['models'] as $modelDetails): ?>
                <li>
                    <a href="#" class="knowledgeBaseElement" data-uri="<?php echo $modelDetails['url'] ?>" about="<?php echo $modelDetails['graphUri'] ?>" <?php if( $modelDetails['selected'] ) echo 'style="text-decoration: underline; font-weight: bold;"' ?>>
                        <?php echo $modelDetails['label'] ?>
                    </a>
                </li>
            <?php endforeach; ?>
        <?php else: ?>
            <li><?php echo $this->_('No knowledge bases found.') ?></li>
        <?php endif; ?>

        <?php if (isset($this->data['create']['allowed']) && $this->data['create']['allowed']): ?>
        <li class="divider"></li>
        <li>
            <a href="<?php echo $this->data['create']['url']; ?>">Create Knowledge Base</a>
        </li>
        <?php endif; ?>
    </ul>
</li>
