<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki model list template
 */

?>
<?php if (!empty($this->models)): ?>
    <ol class="bullets-none separated has-contextmenus-block">
    	<?php foreach ($this->models as $modelDetails): ?>
    		<li>
    			<a class="Model <?php echo $modelDetails['selected'] ?>" href="<?php echo $modelDetails['url'] ?>" about="<?php echo $modelDetails['graphUri'] ?>">
    				<?php echo $modelDetails['label'] ?>
    			</a>
    		</li>
    	<?php endforeach; ?>
    </ol>
<?php else: ?>
    <p class="messagebox info"><?php echo $this->_('No knowledge bases found.') ?></p>
<?php endif; ?>
