<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xml:lang="en"
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <style type="text/css" media="all">
        @import "<?php echo $this->siteConfig['baseuri']?>css/main.css";
    </style>
    <title>Towards a LOD2 site</title>
</head>

<body>
<h1 property="dc:title">Towards a LOD2 site</h1>
<h2><?php echo $this->siteConfig['resourceUri']?> (selected resource)</h2>

<p class="author" rel="dc:creator">
  <span about="http://sebastian.tramp.name" typeof="foaf:Person">
    <span property="foaf:name">Sebastian Tramp</span> ● AKSW<br />
  </span>
  <span typeof="foaf:Person">
    <span property="foaf:name">Norman Heino</span> ● AKSW<br />
  </span>
  <span typeof="foaf:Person">
    <span property="foaf:name">Jonas Brekle</span> ● AKSW<br />
  </span>
</p>

<p class="abstract" property="dc:abstract">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus faucibus ligula a nulla tincidunt hendrerit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas nec dui eget odio venenatis pharetra nec ac erat. Proin ut libero ut diam condimentum pharetra id vel enim. Suspendisse fringilla ullamcorper nunc, id sollicitudin purus blandit et. Quisque pretium neque quis metus ultricies convallis. Donec a rutrum metus. Integer varius pharetra elit, ut tincidunt elit sodales non. Ut varius ante in libero imperdiet a euismod diam tincidunt. Fusce id ligula neque, vel sollicitudin leo. Proin semper lobortis diam, et facilisis tellus egestas in. Sed eu. </p>

<ul>
    <li>Norm: Linked Data URIs auf den site controller forwarden?</li>
    <li><del>Wie wird die Startseite erreichbar (also eigentlich das OW basedir)</del>
        <pre>
index.default.controller = "site"
index.default.action = "lod2"
        </pre>
    </li>
    <li>Seebi: private Config für site modell</li>
    <li>Seebi: Wie werden die Templates pro Klasse benutzt</li>
    <li>Welche view-variablen sind notwendig (mal bei Wordpress schauen)</li>
    <li>Norm: CBD der selected resource?</li>
    <li>Norm: titles über TitleHelper aller in der CBD enthaltenen ressource?</li>
    <li>Wie werden zusatz-libs (php) eingebunden (z.B. für feeds)</li>
        <pre>
require_once ... normal
        </pre>
    <li>Norm: Wie wird modul-content gerendert (eigener context)</li>
        <pre>
kurzes beispiel bitte hier
        </pre>
    <li>Jonas: Wie werden Bilder aus dem CSS referenziert</li>
        <pre>
bitte testen
        </pre>
    <li>...</li>
</ul>

<ul>Später:
    <li>Wie wird der URI helper zur Verfügung gestellt</li>
    <li>Wie werden Dokumente (z.B. PDFs) benutzt (über files component)</li>
</ul>

</body>
</html>