<?php

/**
 * OntoWiki bookmarklet module template
 *
 * @author     Sebastian Dietzold <dietzold@informatik.uni-leipzig.de>
 * @copyright  Copyright (c) 2009, {@link http://aksw.org AKSW}
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

?>
<?php if ($this->has('warningMessage')): ?>
    <p class="messagebox info"><?php echo $this->warningMessage ?></p>
<?php endif; ?>
<?php if ($this->has('infoMessage')): ?>
    <p class="messagebox info"><?php echo $this->infoMessage ?></p>
<?php endif; ?>
<script type="text/javascript" charset="utf-8">
    var saveTitle = 'Save to OntoWiki';
    var windowTitle = 'Extract Triples to OntoWiki at <?php echo $this->ontoWikiUrl ?>';
    // var bmWidgetBase = document.location.href.replace('tests/bookmarklet.html', '');
    var bmWidgetBase = '<?php echo $this->rdfAuthorBase ?>';
    var href = '\
        href="javascript:void((function() {\
        widgetBase = \'' + bmWidgetBase + '\';\
        if (!document.getElementById(\'RDFauthorScript\')) {\
            var s = document.createElement(\'script\');\
            s.type = \'text/javascript\';\
            s.id = \'RDFauthorScript\';\
            s.src = widgetBase + \'src/loader.js\';\
            document.getElementsByTagName(\'head\')[0].appendChild(s);\
        }\
        rdfauthor_loaded_callback = function() {\
            RDFauthor.setOptions({\
                saveButtonTitle: saveTitle,\
                cancelButtonTitle: \'Cancel\',\
                title: windowTitle,\
                showAddPropertyButton: false,\
                defaultGraph: \'<?php echo $this->defaultGraph ?>\',\
                defaultUpdateEndpoint: \'<?php echo $this->defaultUpdateService ?>\',\
                defaultQueryEndpoint: \'<?php echo $this->defaultQueryService ?>\'\
            });\
            RDFauthor.startEditing();\
        };\
    })());"';
    
    // rebuild strings
    document.writeln('<a ' + 
        href.replace(/[\s]/g, '')
            .replace('saveTitle', '\'' + saveTitle + '\'')
            .replace('windowTitle', '\'' + windowTitle + '\'')
            .replace('vars', 'var s') + 
        '>Save to OntoWiki with RDFauthor</a>');
</script>
