<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper
);

$queryObject = new Erfurt_Sparql_SimpleQuery();
$queryObject->setProloguePart('
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX faun: <http://purl.org/net/faunistics#>
PREFIX geof: <http://www.mindswap.org/2003/owl/geo/geoFeatures.owl#>

SELECT COUNT(DISTINCT ?RecordURI) as ?RecordCount ?FamilyComment ?FamilyLabel ?GenusLabel ?SpeciesLabel ?SpeciesURI ?GenusURI ?FamilyURI ?citationSuffix
    ');

$queryObject->setWherePart('
WHERE {

  ?RecordURI faun:identifiesAs ?SpeciesURI.
  {
  ?RecordURI faun:recordedAtLocation <' . $this->resourceUri . '> .
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within <' . $this->resourceUri . '>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within <' . $this->resourceUri . '>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within ?l2.
  ?l2 geof:within <' . $this->resourceUri . '>.
  }

  ?RecordURI faun:identifiesAs ?SpeciesURI.
  ?SpeciesURI faun:subTaxonOf ?GenusURI.
  ?GenusURI faun:subTaxonOf ?FamilyURI.

  ?SpeciesURI rdfs:label ?SpeciesLabel.
  ?SpeciesURI faun:citationSuffix ?citationSuffix.
  ?GenusURI rdfs:label ?GenusLabel.
  ?FamilyURI rdfs:label ?FamilyLabel.
  ?FamilyURI rdfs:comment ?FamilyComment.
}
    ');

$queryObject->setOrderClause('
ASC(?FamilyComment) ?SpeciesLabel
    ');

$queryObject->setLimit('10000');
?>
<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <p><?php echo $this->partial('spiders/content.phtml', $templateData); ?></p>
    </div>
</div>
<div class="box">
    <h2>Checklist</h2>
    <div class="block">
        <table class="checklist">
            <thead>
            <th>Rank</th>
            <th>Species</th>
            <th>Number of Records</th>
            <th>Family</th>
            <th>Genus</th>
            <thead>
            <tbody>
                <?php echo $this->querylist($queryObject, 'spiders/types/checklist-row.phtml'); ?>
            </tbody>
        </table>
    </div>
</div>
