<tr>
    <td><?php echo $this->FamilyComment ?></td>
    <td><a href="<?php echo $this->SpeciesURI ?>"><?php echo $this->SpeciesLabel ?></a> <?php echo $this->citationSuffix ?></td>
    <td><?php echo $this->RecordCount ?></td>
    <td><a href="<?php echo $this->FamilyURI ?>"><?php echo $this->FamilyLabel ?></a></td>
    <td><a href="<?php echo $this->GenusURI ?>"><?php echo $this->GenusLabel ?></a></td>
</tr>
