<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper
);

$queryObject = new Erfurt_Sparql_SimpleQuery();
$queryObject->setProloguePart('
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX faun: <http://purl.org/net/faunistics#>
PREFIX geof: <http://www.mindswap.org/2003/owl/geo/geoFeatures.owl#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>

SELECT ?LocationURI ?RecordURI ?RecordLabel ?RecordType ?FamilyComment ?FamilyLabel ?SpeciesLabel ?SpeciesURI ?FamilyURI ?citationSuffix  ?lat ?long
    ');

$queryObject->setWherePart('
WHERE {
  {
    ?RecordURI faun:publishedIn <' . $this->resourceUri . '> .
  } UNION {
    ?RecordURI faun:citedIn <' . $this->resourceUri . '> .
  }
  ?RecordURI a ?RecordType.

  OPTIONAL {
    ?RecordURI rdfs:label ?RecordLabel.
  }
  ?RecordURI faun:identifiesAs ?SpeciesURI.
  ?RecordURI faun:recordedAtLocation ?LocationURI .

  ?RecordURI faun:identifiesAs ?SpeciesURI.
  ?SpeciesURI faun:subTaxonOf ?GenusURI.
  ?GenusURI faun:subTaxonOf ?FamilyURI.

  ?SpeciesURI rdfs:label ?SpeciesLabel.
  ?SpeciesURI faun:citationSuffix ?citationSuffix.
  ?GenusURI rdfs:label ?GenusLabel.
  ?FamilyURI rdfs:label ?FamilyLabel.
  ?FamilyURI rdfs:comment ?FamilyComment.
  
  OPTIONAL {
    ?LocationURI geo:lat ?lat.
    ?LocationURI geo:long ?long.
  }
}
    ');

$queryObject->setOrderClause('
ASC(?FamilyComment) ?SpeciesLabel
    ');

$queryObject->setLimit('10000');

?>
<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <p><?php echo $this->partial('spiders/content.phtml', $templateData); ?></p>
    </div>
</div>
<div class="box">
    <h2>Map</h2>
    <div class="block">
        <div class="speciesmap">...</div>
    </div>
</div>
<div class="box">
    <h2>Records</h2>
    <div class="block">
        <table class="pchecklist">
            <thead>
            <th>Rank</th>
            <th>Species</th>
            <th>Family</th>
            <th>Location</th>
            <th>Record / Label</th>
            <th>Type</th>
            </thead>
            <tbody>
                <?php echo $this->querylist($queryObject, 'spiders/types/publication-row.phtml'); ?>
            </tbody>
        </table>
    </div>
</div>
