<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki navigation template
 */

#var_dump($this->data);
?>
<form class="width98">
    <label
        class="display-block onlyAural"
        for="navigation-input">Search in Navigation</label>
    <input
        id="navigation-input"
        class="text width99 inner-label"
        type="text"
        value=""
        name="navigation-input"/>
</form>
<div id="navigation-content" class="width99 init-me-please">
<?php
if( isset($this->stateView) ){
    echo $this->stateView;
}
?>
</div>
