<?php

/**
 * OntoWiki navigation template
 *
 *


                    <a class="hasMenu" style="color:black; text-decoration:none; font-style:italic"
                        about="<?php echo $info->getPropertyUri(); ?>"
                        href="<?php echo $info->getPropertyUrl(); ?>" ">
                       <?php echo $this->titleHelper->getTitle($info->getPropertyUri(), $this->locale); ?>
                    </a>


*/
#var_dump($this->data);
?>

<table style ="padding:0px;margin:0px ">
<?php foreach ($this->titles as $property => $titles) : ?>
    <tr><td colspan=2>
            <a class="hasMenu" style="text-decoration:none;"
                        about="<?php echo $property; ?>"
                        href="<?php 
                            $url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
                            $url->setParam('r', $property , true);
                        echo (string) $url ; ?>" >
                <?php echo $this->titleHelper->getTitle($property, $this->locale); ?> </a>
    </td></tr>
    <?php foreach ($titles as $title) : ?>

        <tr><td>[<b> <?php echo $title['lang'] ?> </b>]</td>
            <?php if (!$title['title']) : ?>
                <td><b style="color:red"> <?php echo $this->_('Title is missing') ?> </b></td>
            <?php else : ?>
                <td> <?php echo $title['title'] ?> </td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
<?php endforeach; ?>

</table>