<?php if($this->anon){
echo "Error! You are not logged in.";
}else{ ?>
    <table class="separated-vertical">
        <thead>
            <th>
                News
            </th>
            <th>
                New Plugins
            </th>
        </thead>
        <tbody>
            <tr>
                <td id="newsContainer" width="50%">
					<img src="<?php echo $this->themeUrlBase; ?>images/spinner.gif" style="margin: 50px;"/> <!-- News inserted by AJAX here -->
                </td>
                <td id="pluginsContainer" width="50%">
					<img src="<?php echo $this->themeUrlBase; ?>images/spinner.gif" style="margin: 50px;"/> <!-- Plugins inserted by AJAX here -->
                </td>
            </tr>
        </tbody>
    </table>
<?php } ?>