<ul>
<?php
/**
 * A function for making time periods readable
 *
 * @author      Aidan Lister <aidan@php.net>
 * @version     2.0.1
 * @link        http://aidanlister.com/2004/04/making-time-periods-readable/
 * @param       int     number of seconds elapsed
 * @param       string  which time periods to display
 * @param       bool    whether to show zero time periods
 */
function time_duration($seconds, $use = null, $zeros = false)
{
    // Define time periods
    $periods = array (
        'years'     => 31556926,
        'Months'    => 2629743,
        'weeks'     => 604800,
        'days'      => 86400,
        'hours'     => 3600,
        'minutes'   => 60,
        'seconds'   => 1
        );

    // Break into periods
    $seconds = (float) $seconds;
    $segments = array();
    foreach ($periods as $period => $value) {
        if ($use && strpos($use, $period[0]) === false) {
            continue;
        }
        $count = floor($seconds / $value);
        if ($count == 0 && !$zeros) {
            continue;
        }
        $segments[strtolower($period)] = $count;
        $seconds = $seconds % $value;
    }

    // Build the string
    $string = array();
    foreach ($segments as $key => $value) {
        $segment_name = substr($key, 0, -1);
        $segment = $value . ' ' . $segment_name;
        if ($value != 1) {
            $segment .= 's';
        }
        $string[] = $segment;
    }

    return implode(', ', $string);
}
$i=1; $odd = true;
foreach ($this->instanceInfo as $instanceUri => $instance){
            echo $this->partial('partials/list_community_item.phtml',
                array(
                    'instanceUri'  => $instanceUri,
                    'instance'     => $instance,
                    'instanceData' => $this->instanceData,
                    'instanceInfo' => $this->instanceInfo,
                    'propertyInfo' => $this->propertyInfo,
                    'other'        => $this->other,
                    'odd'          => $odd,
                    'i'            => $i
                )
             );
            $odd = !$odd;
            $i++;
        } ?>
</ul>