    <tr
        about="<?php echo $this->comment ?>"
        resource="<?php echo $this->comment ?>"
        class="Resource community-item comment <?php echo $this->odd ? 'odd' : 'even'; ?>"
    >
        <td>
            <strong><?php echo $this->author ?></strong> on 
            <a
                about="<?php echo $this->resource ?>"
                resource="<?php echo $this->resource ?>"
                class="Resource hasMenu"
                href="<?php echo $this->resourceUrl ?>"
            ><?php echo $this->resourceName ?></a>
            <span class="date" style="color:#aaa;font-size:0.9em">(<?php echo $this->date ?>)</span>:
            <?php echo $this->content ?>
        </td>
    </tr>
