<?php
$author = $this->author;
if ($author === null) {
    $author = '<em>anonymous</em>';
}
?>
    <tr
        about="<?php echo $this->comment ?>"
        resource="<?php echo $this->comment ?>"
        class="Resource community-item comment <?php echo $this->odd ? 'odd' : 'even'; ?>"
    >
        <td>
            <div class="has-contextmenu-area">
                <div class="contextmenu">
                    <a href="<?php echo $this->commentUrl ?>"
                        class="item">
                        <span class="icon icon-arrow-next" title="Jump to resource">
                            <span>Jump to resource</span>
                        </span>
                    </a>
                </div>
                <strong><?= $author ?></strong>
                <?php if (isset($this->resource)) : ?>
                on 
                <a
                    about="<?php echo $this->resource ?>"
                    resource="<?php echo $this->resource ?>"
                    class="Resource hasMenu"
                    href="<?php echo $this->resourceUrl ?>"
                ><?php echo $this->resourceName ?></a>
                <?php endif; ?>
                <span class="date">(<?php echo $this->date ?>)</span>:
                <?php echo $this->content ?>
            </div>
        </td>
    </tr>
