<?php
/**
 * A function for making time periods readable
 *
 * @author      Aidan Lister <aidan@php.net>
 * @version     2.0.1
 * @link        http://aidanlister.com/2004/04/making-time-periods-readable/
 * @param       int     number of seconds elapsed
 * @param       string  which time periods to display
 * @param       bool    whether to show zero time periods
 */
function time_duration($seconds, $use = null, $zeros = false)
{
    // Define time periods
    $periods = array (
        'years'     => 31556926,
        'Months'    => 2629743,
        'weeks'     => 604800,
        'days'      => 86400,
        'hours'     => 3600,
        'minutes'   => 60,
        'seconds'   => 1
        );

    // Break into periods
    $seconds = (float) $seconds;
    $segments = array();
    foreach ($periods as $period => $value) {
        if ($use && strpos($use, $period[0]) === false) {
            continue;
        }
        $count = floor($seconds / $value);
        if ($count == 0 && !$zeros) {
            continue;
        }
        $segments[strtolower($period)] = $count;
        $seconds = $seconds % $value;
    }

    // Build the string
    $string = array();
    foreach ($segments as $key => $value) {
        $segment_name = substr($key, 0, -1);
        $segment = $value . ' ' . $segment_name;
        if ($value != 1) {
            $segment .= 's';
        }
        $string[] = $segment;
    }

    return implode(', ', $string);
}
?>

<li>
    <?php if($this->instance['type'] == 'uri'){
        $entry = $this->instanceData[$this->instanceUri];

        ?>
        <div class="community-item">
            <h3  class="name"><a href="<?php echo $this->instance['url'] ?>"><?php echo $this->instance['title'] ?></a></h3>
            <p class="creator"><?php echo $this->instanceData[$this->instanceUri]['creator'][0]['value']; ?> said</p>
            <p class="content"><?php echo $this->instanceData[$this->instanceUri]['content'][0]['value']; ?></p>
            <?php if(isset($this->instanceData[$this->instanceUri]['about'])){ ?><p class="about"><?php echo $this->instanceData[$this->instanceUri]['about'][0]['title']; ?></p><?php } ?>
            <p class="date"><?php echo time_duration(time() - strtotime($this->instanceData[$this->instanceUri]['date'][0]['value'])); ?> ago</p>
        </div>
    <?php } ?>
</li>
