<table class="separated-vertical">
    <tr>
        <?php if(!$this->singleResource) { ?> <th width="30%"><?php echo $this->_('Resource') ?></th> <?php } ?>
        <th width="30%"><?php echo $this->_('Author') ?></th>
        <th width="70%"><?php echo $this->_('Comment') ?></th>
    </tr>
    <?php foreach($this->comments as $comment): ?>
        <tr class="comment">
            <?php if(!$this->singleResource) { ?> <td><a href="<?php echo $comment['url'] ?>"><?php echo $this->titles->getTitle($comment['resource']); ?></a></td> <?php } ?>
            <td><?php echo $comment['author'] ?> <span style="color:#aaa;font-size:0.9em">(<?php echo $comment['date'] ?>)</span></td>
            <td><?php echo $comment['content'] ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<?php
    if($this->singleResource) {
        $this->placeholder('main.window.innerwindows')->append($this->module('comment'));
    }
?>