<form action="<?php echo $this->actionUrl ?>" method="post" accept-charset="utf-8" name="comment" class="ajaxForm reloadOnSuccess">
    <fieldset>
        <textarea style="min-width:50%;min-height:4.5em" class="width99" name="c"></textarea>
    </fieldset>
    <a class="button submit">
        <img src="<?php echo $this->themeUrlBase ?>/images/icon-comment-add.png" alt="add comment icon" />
        <span><?php echo $this->_('Post Comment') ?></span>
    </a>
</form>

