<?php

/**
 * OntoWiki navigation partial template
 *
 * @author  Norman Heino <norman.heino@gmail.com>
 * @author  Michael Haschke
 * @version $Id: navigation.phtml 2890 2009-04-20 09:45:38Z norman.heino $
 */

?>
<?php $i = 0 ?>
<?php if ($this->has('navigation')): ?>
    <ul class="nav nav-tabs">
        <?php foreach ($this->navigation as $key => $config): ?>
            <li id="<?php echo $key ?>" class="<?php echo isset($config['active']) ? 'active' : '' ?>">
                <a href="<?php echo $config['url'] ?>"><?php echo $this->_($config['name']) ?></a>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
