<?php

/**
 * OntoWiki menu partial template
 *
 * @author  Norman Heino <norman.heino@gmail.com>
 * @author  Michael Haschke
 * @version $$
 */

?>
<?php if ($this->has('statusbar')): ?>
    <div class="alert alert-info">
        <?php $i=0; foreach ($this->statusbar as $statusElement): ?>
            <div class="statustool" <?php if(++$i != count($this->statusbar) ) echo 'style="float:left;"'; ?> ><?php echo $statusElement ?></div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
