<div>
<!--  OLD LIST
<table class="separated-vertical">
<?php $odd = true;?>
<thead>
    <tr class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
        <th>id</th>
        <th>label</th>
        <th>view pattern</th>
        <th>execute pattern</th>
    </tr>
</thead>
<tbody>
	<?php
	    $n = 0;
	    foreach ($this->data as $part) {
	?>
	<tr class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
	    <td><?php echo sprintf('%04d',++$n);?></td>
	    <td><?php echo $part['label'];?></td>
	    <td><a href="<?php echo $part['view_url']; ?>"><?php echo 'open in editor';?></a></td>
	    <td><a href="<?php echo $part['exec_url']; ?>"><?php echo 'open for execution';?></a></td>
	</tr>
	<?php
	    }
	?>
</tbody>
</table>
 -->
</div>