<div id="patternmanager" class="ePatternExecution">

    <fieldset class="ePatternExecution">

        <h2>{Name des Pattern}</h2>

        <p class="abstract">
            {Lorem Ipsum Semantic Kauderwelsch, hier kommt die Beschreibung des Patterns hin.}
        </p>

        <fieldset>

            <legend>Input</legend>

            <?php foreach ($this->variables as $var): ?>
            <div class="row-input input-justify-left">
                <label for="var[<?php echo $var['name']; ?>]"><?php echo $var['name']; ?></label>
                <input
                    type="text"
                    class="text pm_var"
                    name="var[<?php echo $var['name']; ?>]"
                    id="var[<?php echo $var['name']; ?>]"
                    <?php if ($var['prebound'] !== false):
                        echo 'value="'. $var['prebound'] . '"' . PHP_EOL;
                        echo 'readonly';
                    endif; ?>
            	/>
                <label for="var[<?php echo $var['name']; ?>]" class="vartype">
                    <span class="onlyAural">(type: </span><span class="vartypename"><?php echo $var['type']; ?></span<span class="onlyAural">)</span>
                </label>
                <br class="clearall"/>
                <p class="messagebox info">{Infotext/Beschreibung zur Variablen.}</p>
            </div>
            <?php endforeach; ?>

        </fieldset>


        <?php if ( defined('_OWDEBUG') ): ?>
        <fieldset>

            <legend>Output/Debug</legend>

            <?php if (!empty($this->microtime)): ?>
                <p class="messagebox info">Execution time: <?php echo $this->microtime; ?></p>
            <?php endif; ?>

        </fieldset>
        <?php endif; ?>

    </fieldset>

</div>
