<div>
<table>
<thead>
</thead>
<tbody>
    <?php 
        foreach ($this->variables as $var) {
    ?>
    <tr>
	    <td><?php echo $var['varname']; ?></td>
	    <td><input type="text" class="text" name="var[<?php echo $var['varname']; ?>]" id="var[<?php echo $var['varname']; ?>]"/></td>
	    <td><?php echo $var['type']; ?></td>
    </tr>
    <?php
        }
    ?>
</tbody>
</table>
<?php
    if ( defined('_OWDEBUG') ) {
?>
<p class="messagebox warning">
    execution took: <?php echo $this->microtime; ?>
</p>
<?php 
    }
?>
</div>