<div>
	<p style="margin: 5px 10px;">
		<a class="button" style="width: 100px;" href="<?php echo $this->url['browse'];?>">
			<img src="<?php echo $this->componentUrlBase . 'img/browse.png'; ?>"/>
			<span>BROWSE</span>
		</a>
        Browse existing patterns
	</p>
	<p style="margin: 5px 10px;">
		<a class="button" style="width: 100px;" href="<?php echo $this->url['view']; ?>">
		    <img src="<?php echo $this->componentUrlBase . 'img/edit.png'; ?>"/>
		    <span>NEW</span>
		</a>
        Create a new pattern
	</p>
    <p style="margin: 5px 10px;">
        <a class="button" style="width: 100px;" href="<?php echo $this->url['browse']; ?>">
            <img src="<?php echo $this->componentUrlBase . 'img/edit.png'; ?>"/>
            <span>EDIT</span>
        </a>
        Edit an existing pattern
    </p>
</div>