<div id="patternmanager">
    <a href="javascript:addPMPattern();">add</a> <br/>
    Name for ComplexPattern: <input type="text" class="text width95" name="label" id="label" value="Pattername"/>
    Description for ComplexPattern: <input type="text" class="text width95" name="desc" id="desc" value="Patterndesc"/>
    <div style="display:none;" id="subpattern">
        <a href="javascript:hidePMPattern();">hide</a>
        <a href="javascript:showPMPattern();">show</a>
        <a href="javascript:delPMPattern();">del</a>
        <div>
            Name for SubPattern: <input type="text" class="BasicPattern text width95" name="patternlabel-" id="patternlabel-" value=""/>
        	Description for SubPattern: <input type="text" class="text width95" name="patterndesc-" id="patterndesc-" value=""/>
        </div>
        <table>
            <thead>
            <tr>
            <th>Variablename</th>
            <th>Variabletype</th>
            <th>Variabledescription</th>
            <th style="text-align:right;"><a href="javascript:addPMvar();">add</a></th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>
                <input class="text width95" type="text" name="varname-" id="varname-"/>
            </td>
            <td>
                <select  name="vartype-" id="vartype-" size="1">
	               <option>RESOURCE</option>
        	       <option>LITERAL</option>
                   <option>TEMP</option>
                   <option>GRAPH</option>
                   <option>LANG</option>
                   <option>DATATYPE</option>
                   <option>CLASS</option>
	               <option>PROPERTY</option>
                    <!--
                    <option>REGEXP</option>
                    <option>vvv</option>
                    -->
                </select>
                <!--<input type="text" class="text" name="vartype-" id="vartype-"/>-->
            </td>
            <td>
                <input class="text width95" type="text" name="vardesc-" id="vardesc-"/>
            </td>
            <td style="text-align:right;">
                <a href="javascript:delPMvar();">del</a>
            </td>
            </tr>
            </tbody>
        </table>
        <table>
            <thead>
            <tr>
            <th>Selectquery</th>
            <th  style="text-align:right;"><a style="display:none;" href="javascript:addPMselect();">add</a></th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>
                <input class="text width95" type="text" name="selectpattern-" id="selectpattern-"/>
            </td>
            <td  style="text-align:right;">
                <a href="javascript:delPMselect();">del</a>
            </td>
            </tr>
            </tbody>
        </table>
        <table>
            <thead>
            <tr>
            <th>Inserttriples</th>
            <th style="text-align:right;"><a href="javascript:addPMinsert();">add</a></th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>
                <input class="text width95" type="text" name="insertpattern-" id="insertpattern-"/>
            </td>
            <td style="text-align:right;">
                <a href="javascript:delPMinsert();">del</a>
            </td>
            </tr>
            </tbody>
        </table>
        <table>
            <thead>
            <tr>
            <th>Deletetriples</th>
            <th style="text-align:right;"><a href="javascript:addPMdelete();">add</a></th>
            </tr>
            </thead>
            <tbody>
            <tr>
            <td>
                <input class="text width95" type="text" name="deletepattern-" id="deletepattern-"/>
            </td>
            <td style="text-align:right;">
                <a href="javascript:delPMdelete();">del</a>
            </td>
            </tr>
            </tbody>
        </table>
        </div>
        
</div>

<?php if ( !empty($this->jsonPattern) && is_string($this->jsonPattern) )  { ?>
<script type="text/javascript">
// jQuery Json used here (compatible)
var jsonPattern = $.secureEvalJSON(<?php echo '\'' . addcslashes($this->jsonPattern,'\'') . '\''; ?>);

label = jsonPattern['label'];
desc = jsonPattern['desc'];

$('div#patternmanager > input#label').val(label);
$('div#patternmanager > input#desc').val(desc);

for (key in jsonPattern['subPattern']) {

    label = jsonPattern['subPattern'][key]['label'];
    desc  = jsonPattern['subPattern'][key]['desc'];
    
    addPMPattern(label,desc);

    i = parseInt(key) + 1;
    current = jsonPattern['subPattern'][key];
    for (t in current) {
        if (t == 'V') {
            delPMvar(i,1);
            for (v in current[t]) {
                addPMvar(i,null,current[t][v]['name'],current[t][v]['type'],current[t][v]['desc']);
            }
        } else if (t == 'S') {
            delPMselect(i,1);
            for (v in current[t]) {
                addPMselect(i,null,current[t][v]);
            }
        } else if (t == 'U') {
            delPMinsert(i,1);
            delPMdelete(i,1);
            for (pkey in current[t]) {
                if (current[t][pkey]['type'] === 'insert' ) {
                    addPMinsert(i, null, current[t][pkey]['pattern']);
                } else if ( current[t][pkey]['type'] === 'delete' ) {
                    addPMdelete(i, null, current[t][pkey]['pattern']);
                } else {
                    // do nothing
                }
            }
        }
    }
}
</script>

<?php } ?>
<?php if ( !empty($this->errorPattern) && is_string($this->errorPattern) )  { ?>
<script type="text/javascript">
// jQuery Json used here (compatible)
var errorpattern = $.secureEvalJSON(<?php echo '\'' . $this->errorPattern . '\''; ?>);
for (i in errorpattern) {
    $('#' + errorpattern[i]).css('background-color','#FF7070').css('color','#FAFAFA');
}
</script>

<?php } ?>
