<?php
// this is the standard template data
$templateData = array(
    'title'             => $this->title,
    'resourceUri'       => $this->resourceUri,
    'description'       => $this->description,
    'descriptionHelper' => $this->descriptionHelper
);

$nature = isset($this->description['http://lod2.eu/schema/deliverableNature'][0]['value'])
          ? $this->description['http://lod2.eu/schema/deliverableNature'][0]['value']
          : null;

          $level = isset($this->description['http://lod2.eu/schema/disseminationLevel'][0]['value'])
       ? $this->description['http://lod2.eu/schema/disseminationLevel'][0]['value']
       : null;

$workPackage = isset($this->description['http://lod2.eu/schema/wp'][0]['value']) 
             ? $this->description['http://lod2.eu/schema/wp'][0]['value'] 
             : null;

$date = null;
if (isset($this->description['http://lod2.eu/schema/deliveryDate'][0]['value'])) {
    $d = new DateTime($this->description['http://lod2.eu/schema/deliveryDate'][0]['value']);
    $date = $d->format('j F Y');
}
?>

<div class="maincontent">
    <div class="section deliverable">
        <h3><?php echo $this->title ?></h3>
        <div class="section-content">
            <?php echo $this->partial('lod2/content.phtml', $templateData); ?>
            <?php if ($workPackage): ?>In workpackage: <a href="<?php echo $this->url($workPackage); ?>"><?php 
                echo $this->descriptionHelper->getTitle($workPackage); ?></a><?php endif; 
            ?>
            <?php if ($date): ?>Delivery date: <?php echo $date; endif; ?>
            <ul>
                <li><?php if ($nature): ?>Delivarable nature: <?php echo $nature; endif; ?></li>
                <li><?php if ($level): ?>Dissemination level: <?php echo $level; endif; ?></li>
            </ul>
        </div>
    </div>
</div>