<?php
// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper
        );
?>
<div class="maincontent">
    <div class="section partner">
        <h3><?php echo $this->title ?></h3>
        <div class="section-content">
            <?php echo $this->partial( 'lod2/content.phtml', $templateData); ?>
        </div>
    </div>
</div>


<?php // WORKPACKAGES

$query = '
PREFIX lod2: <http://lod2.eu/schema/>
SELECT DISTINCT ?resourceUri
WHERE {
?resourceUri lod2:partner <'.$this->resourceUri.'> .
?resourceUri a lod2:WorkPackage.
FILTER (!isBLANK(?resourceUri))
}
LIMIT 10
​';

if ($workpackages = $this->querylist($query, 'lod2/items/li.phtml')): ?>

<div class="c50l">
    <div class="subcl widget-deeplink">
        <h3>Workpackages</h3>
         <ul>
            <?php echo $workpackages ?>
         </ul>
    </div>
</div>

<?php endif; ?>
