<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <div class="project article first">
            <?php if (isset($this->description['http://rdfs.org/sioc/ns#content'])) : ?>
                <?php echo $this->description['http://rdfs.org/sioc/ns#content'][0]['value']; ?>
            <?php endif ?>

            <p class="meta">
            <?php echo $this->partial( 'lod2/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>
            </p>
        </div>
    </div>
</div>
