<?php

/**
 * OntoWiki navigation entry list template
 */
$odd = true;
?>
    <?php if (! (isset($this->showRoot) && $this->showRoot == false) ):?>
        <li class="nav-header">
        <?php if (isset($this->rootEntry)):?>
            <a class="navFirst icon-arrow-first" title="Go to root level"></a>
			<a class="navBack icon-arrow-previous" title="Go to previous level"></a>
            <a class="hasMenu" href="<?php echo $this->rootEntry['url'] ?>" about="<?php echo $this->rootEntry['uri'] ?>">
                <?php echo $this->rootEntry['title'] ?>
            </a>
        <?php else: ?>
            <?php if ( isset($this->rootName) ){
                if( isset($this->rootLink) ){
                   echo '<a class="navigation" href="'.$this->rootLink.'" >';
                   echo $this->rootName;
                   echo '</a>';
                }else{
                    echo $this->rootName;
                }
            } ?>
        <?php endif ?>
        </li>
    <?php endif ?>

    <?php if (!empty($this->messages)): ?>
        <?php foreach ($this->messages as $message): ?>
        <li class="nav-header <?php echo $message['type'] ?>">
            <?php echo $message['text'] ?>
        </li>
        <?php endforeach; ?>
    <?php endif ?>


    <?php if ($this->entries) :?>
        <li>
        <?php foreach ($this->entries as $uri => $entry): ?>
	        <a class="navigation navList"
	           href="<?php echo $entry['link'] ?>"
	           about="<?php echo $uri ?>" title="show list of instances">
	           <?php echo $entry['title'] ?>

	           <?php if( $entry['sub'] > 0 ): ?>
	           <span class="navDeeper navDeeperIcon icon-arrow-next" title="show deeper level"></span>
	           <?php endif ?>
	        </a>
        <?php endforeach; ?>
        </li>
    <?php endif; ?>

<?php if ($this->showMeMore) :?>
<li>
	<a class="btn" href="javascript:navigationEvent ('more', '')" id="naviganion-more">
		<span class="icon-arrow-down"></span> Show Me More
	</a>
</li>
<?php endif; ?>
