<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org content template
 *
 * this template renders the main content (e.g. main textarea) of a resource
 */
?>
<?php if (isset($this->description['http://xmlns.com/foaf/0.1/depiction'])): ?>
    <img rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/depiction') ?>"
         src="<?php echo $this->description['http://xmlns.com/foaf/0.1/depiction'][0]['value'] ?>"
         alt="Depiction of <?php echo htmlentities($this->title) ?>"
         class="depiction"/>
<?php endif; ?>

<?php if (isset($this->description['http://lod2.eu/schema/content'])) : ?>
    <div property="<?php echo $this->curie('http://lod2.eu/schema/content') ?>"><?php
        echo $this->processtidy($this->description['http://lod2.eu/schema/content'][0]['value']);
    ?></div>
<?php elseif (isset($this->description['http://rdfs.org/sioc/ns#content'])) : ?>
<p property="<?php echo $this->curie('http://rdfs.org/sioc/ns#content') ?>">
    <?php echo strip_tags($this->description['http://rdfs.org/sioc/ns#content'][0]['value']); ?>
</p>
<?php endif; ?>

<?php if (isset($this->description['http://lod2.eu/schema/contentRaw'])) : ?>
    <div property="<?php echo $this->curie('http://lod2.eu/schema/contentRaw') ?>"><?php
        echo $this->description['http://lod2.eu/schema/contentRaw'][0]['value'];
    ?></div>
<?php endif; ?>
