<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org layout template
 *
 * the most out template layer
 */

// this is the standard template data
$templateData = array(
    'title' => $this->descriptionHelper->getTitle($this->resourceUri),
    'resourceUri' => $this->resourceUri,
    'description' => $this->description[$this->resourceUri],
    'descriptionHelper' => $this->descriptionHelper,
    'options'           => $this->options
);
?><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUri ?>" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link
        rel="stylesheet" type="text/css" media="all"
        href="<?php echo $this->baseUri ?>/css/styleimports.css"
        title="Standard" />

    <!--[if lte IE 6]>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/patches/ie6.css" media="all" />
    <![endif]-->

    <!-- jQuery -->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>

    <!--script type="text/javascript" src="<?php echo $this->libraryUrlBase ?>RDFauthor/src/rdfauthor.js"></script-->

    <title><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?> &mdash; <?php echo $this->site['name'] ?></title>

<?php
    // includes the GA header script
    $this->headScriptGoogleAnalytics('UA-241023-8');
    // includes the exhibit header links
    $this->headScriptExhibit();
    // other head scripts
    $this->headScript();
?>
</head>
<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>

<?php echo $this->partial('aksw2010/main.phtml', $templateData) ?>
<?php // echo $this->partial('aksw2010/query.phtml', $templateData) ?> <!-- Related Query -->
<?php //echo $this->partial('aksw2010/feed.phtml', $templateData) ?> <!-- NEWS -->
<?php echo $this->partial('aksw2010/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>

</body>
</html>

