<?php
    // this is the standard template data
    $templateData = array(
                    'title' => $this->descriptionHelper->getTitle($this->resourceUri),
                    'resourceUri' => $this->resourceUri,
                    'description' => $this->description[$this->resourceUri],
                    'descriptionHelper' => $this->descriptionHelper,
                    'options'           => $this->options
            );
?><?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUri ?>" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/styleimports.css" media="all" title="Standard" />
    <!--[if lte IE 6]>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/patches/ie6.css" media="all" />
    <![endif]-->

    <!-- jQuery -->
    <!--script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script-->

    <!--script type="text/javascript" src="<?php echo $this->libraryUrlBase ?>RDFauthor/src/rdfauthor.js"></script-->

    <!--script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-fluid16.js"></script-->

    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.cycle.js"></script>

    <title><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?> &mdash; <?php echo $this->site['name'] ?></title>

    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-241023-23']);
      _gaq.push(['_trackPageview']);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
<?php
    // check for exhibit data URI and integrate this as well as exhibit
    if (isset($this->description[$this->resourceUri]['http://lod2.eu/schema/exhibitData'])) {
        echo '  <script src="http://static.simile.mit.edu/exhibit/api-2.0/exhibit-api.js" type="text/javascript"></script>' .PHP_EOL;
        foreach ($this->description[$this->resourceUri]['http://lod2.eu/schema/exhibitData'] as $property) {
            if (isset($property['value'])) {
                echo '  <link href="'.$property['value'].'" type="application/jsonp" rel="exhibit/data" ex:jsonp-callback="cb" />' .PHP_EOL;
            }
        }
    }
?>
    <?php $this->headScript() ?>
</head>
<body<?php
    foreach ($this->namespaces as $prefix => $ns): ?><?php echo ' xmlns:' . $prefix . '="' . $ns . '"' ?><?php endforeach; ?>>


<h1><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?></h1>

<?php echo $this->partial('aksw2010/main.phtml', $templateData) ?>
<?php // echo $this->partial('aksw2010/query.phtml', $templateData) ?> <!-- Related Query -->
<?php //echo $this->partial('aksw2010/feed.phtml', $templateData) ?> <!-- NEWS -->
<?php echo $this->partial('aksw2010/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>

</body>
</html>

