<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * aksw.org main template
 *
 * This template does not output anything but selects a specific partial output
 * for a class (or a default partial)
 */

// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper,
    'options'           => $this->options
);

if (isset($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'])) {
    $types = array();
    foreach ($this->description['http://www.w3.org/1999/02/22-rdf-syntax-ns#type'] as $property) {
        if ((isset($property['value'])) && (Erfurt_Uri::check($property['value']))) {
            $types[$property['value']] = true;
        }
    }

    switch (true) {
        case (isset($types['http://lod2.eu/schema/Demo'])):
            echo $this->partial('lod2/types/demo.phtml', $templateData);
            break;
        default:
            // no specific template found
            echo $this->partial( 'aksw2010/default.phtml', $templateData);
            break;
    }
}
