<?php

/**
 * OntoWiki sparqloptions template
 *
 * @version $Id: sparqloptions.phtml 2522 2009-02-02 10:07:57Z norman.heino $
 */

?>
<div>
	<input type="radio" class="radio" name="result_format" id="result_format_plain" value="plain"
	    <?php if ($this->placeholder('sparql.result.format') == 'plain'): ?>
	        <?php echo ' checked="checked"' ?>
	    <?php endif; ?>
	/>
	<label for="result_format_plain" class="checkboxradio"><?php echo $this->_('Plain') ?></label>
	<br class="clearall" />
	<input type="radio" class="radio" name="result_format" id="result_format_xml" value="xml"
	<?php if ($this->placeholder('sparql.result.format') == 'xml'): ?>
        <?php echo ' checked="checked"' ?>
    <?php endif; ?>
	/>
	<label for="result_format_xml" class="checkboxradio"><a href="http://www.w3.org/TR/rdf-sparql-XMLres/">XML</a></label>
	<br class="clearall">
	<input type="radio" class="radio" name="result_format" id="result_format_json" value="json"
	<?php if ($this->placeholder('sparql.result.format') == 'json'): ?>
        <?php echo ' checked="checked"' ?>
    <?php endif; ?>
	/>
	<label for="result_format_json" class="checkboxradio"><a href="http://www.w3.org/TR/rdf-sparql-json-res/">JSON</a></label>
	<br class="clearall">
</div>
