<?php 
	if ( empty($this->listData) ) { ?>
    <p class="messagebox info"><?php echo $this->_('No matches.'); ?> </p>
<?php } else { ?>
    <table class="separated-vertical">
        <thead>

            <th><?php echo $this->_('querytitle'); ?></th>
            <th><?php echo $this->_('link'); ?></th>
			<th><?php echo $this->_('by user'); ?></th>
            <th><?php echo $this->_('at'); ?></th>
        </thead>
        <tbody>

        <?php $evenOdd = 'even'; ?>
        <?php foreach ($this->listData as $entry) { ?>
            <?php $evenOdd = ($evenOdd === 'even') ? 'odd' : 'even'; ?>  
            <tr class="<?php echo $evenOdd; ?>">

                <td><?php echo $entry['dc:title']; ?></td>
                <td>
					<?php 
						$base = $this->urlBase."querybuilder/manage";
						$base .= "?patterns=".htmlentities($entry['sioc:content']);
						$base .= "&label = ".$entry['dc:title'];
					?>
					<a href="<?php echo $base;?>">Open</a>
					<!--Only uncomment line below if it is working-->
                    <!--<form action="<?php echo $this->_config->urlBase; ?>" method="post">
                        <input type="hidden" name="patterns" value="<?php echo htmlentities($entry['sioc:content']); ?>">
                    <a class="minibutton submit"> submit </a>
                    </form>-->
                </td>
				<td><?php echo $entry['sioc:has_creator']; ?></td>
                <td><?php echo $entry['dc:created']; ?></td>
                <!-- <td><?php print_r($entry); ?></td> -->

            </tr>
        <?php } ?>

        </tbody>
    </table>
<?php } ?>
