<!--script type="text/javascript">
	$(function() {
		$("#accordion").accordion();
	});
</script-->
<div class="block">
    <div class="block" id="accordion">
        <div id="accordion">
        <?php $entrycount = 0; foreach ($this->entries as $entry) : ?>
            <div class="article <?php if ($entrycount == 0) echo 'first' ?>">
                <h3 class="toggler atStart"><?php echo $entry['title'] ?></h3>
                <div class="element atStart">
                    <p class="meta">
                        <a title="permalink"
                           class="hasMenu Resource"
                           about="<?php echo $entry['link'] ?>"
                           href="<?php echo $entry['link'] ?>">
                            <?php echo $entry['dateModified'] ?> |
                            <?php $authors = $entry['authors']; echo $authors[0] ?>
                        </a>
                    </p>
                    <p><?php echo $entry['description'] ?></p>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>
