<!--script type="text/javascript">
	$(function() {
		$("#accordion").accordion();
	});
</script-->
<div class="block">
    <div class="block" id="accordion">
        <div id="accordion"> <?php // TODO: it is invalid XHTML if IDs are used more than once! ?>
        <?php $entrycount = 0; foreach ($this->entries as $entry) : ?>
            <div class="article <?php if ($entrycount == 0) echo 'first' ?>">
                <h3 class="toggler atStart"><?php echo $entry['title'] ?></h3>
                <div class="element atStart">
                    <p class="meta">
                        <a title="permalink"
                           class="hasMenu Resource"
                           about="<?php echo $entry['link'] ?>"
                           href="<?php echo $entry['link'] ?>">
                            <?php if (isset($entry['dateModified'])) :?>
                                <?php echo $entry['dateModified'] ?>
                            <?php endif; ?>
                            <?php if (isset($entry['authors'][0])) :?>
                                <?php if (is_array($entry['authors'][0]) && isset($entry['authors'][0]['name'])): ?>
                                    | <?php echo $entry['authors'][0]['name'] ?>
                                <?php else: ?>
                                    | <?php echo $entry['authors'][0] ?>
                                <?php endif; ?>
                            <?php endif; ?>
                        </a>
                    </p>
                    <?php if ( (isset($entry['description'])) && ($entry['description'] != $entry['title']) ):?>
                        <p><?php echo str_replace('[...]', '', substr(strip_tags($entry['description']), 0, 500)) ?> ...</p>
                    <?php endif; ?>
                </div>
            </div>
        <?php endforeach; ?>
        </div>
    </div>
</div>