<div id="newsfeed" class="block hfeed">
    <?php $entrycount = 0; foreach ($this->entries as $entry) : ?>
        <div class="hentry article <?php if ($entrycount == 0) echo 'first' ?>">
            <h3><a class="hasMenu Resource"
                   about="<?php echo $entry['link'] ?>"
                   href="<?php echo $entry['link'] ?>"><?php echo $entry['title'] ?></a></h3>
            <p class="meta hideme">
                <?php echo $entry['dateModified'] ?> |
                <?php $authors = $entry['authors']; echo $authors[0] ?>
            </p>
            <p>
                <?php
                    echo substr($entry['description'], 0, 200).'...'.PHP_EOL;
                    echo '<a href="'.$entry['link'].'" title="read article &quot;'.htmlspecialchars($entry['title']).'&quot;">read more</a>'
                ?>
            </p>
        </div>
    <?php endforeach; ?>
</div>
