<?php
// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
        );
?>
<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <div class="article first">
            <?php echo $this->partial( 'lod2/content.phtml', $templateData); ?>
            <p class="meta">
                <?php echo $this->partial( 'lod2/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>
            </p>
        </div>
    </div>
</div>

<div class="grid_4">
    <div class="box">
        <h2>Milestones</h2>
        <?php
            $query = '
PREFIX lod2: <http://lod2.eu/schema/>.
SELECT DISTINCT ?resourceUri
WHERE {
?resourceUri lod2:wp <'.$this->resourceUri.'> .
?resourceUri a lod2:Milestone
FILTER (!isBLANK(?resourceUri))
}
LIMIT 10
​';
            echo $this->querylist($query, 'lod2/items/li.phtml');
        ?>
    </div>
</div>

<div class="grid_4">
    <div class="box">
        <h2>Tasks</h2>
        <?php
            $query = '
PREFIX lod2: <http://lod2.eu/schema/>.
SELECT DISTINCT ?resourceUri
WHERE {
?resourceUri lod2:wp <'.$this->resourceUri.'> .
?resourceUri a lod2:Task
FILTER (!isBLANK(?resourceUri))
}
LIMIT 10
​';
            echo $this->querylist($query, 'lod2/items/li.phtml');
        ?>
    </div>
</div>

<div class="grid_4">
    <div class="box">
        <h2>Deliverables</h2>
        <?php
            $query = '
PREFIX lod2: <http://lod2.eu/schema/>.
SELECT DISTINCT ?resourceUri
WHERE {
?resourceUri lod2:wp <'.$this->resourceUri.'> .
?resourceUri a lod2:Deliverable
FILTER (!isBLANK(?resourceUri))
}
LIMIT 10
​';
            echo $this->querylist($query, 'lod2/items/li.phtml');
        ?>
    </div>
</div>

<div class="grid_4">
    <div class="box">
        <h2>Partner</h2>
        <?php
            $query = '
PREFIX lod2: <http://lod2.eu/schema/>.
SELECT DISTINCT ?resourceUri
WHERE {
<'.$this->resourceUri.'> lod2:partner ?resourceUri.
?resourceUri a lod2:Partner
FILTER (!isBLANK(?resourceUri))
}
LIMIT 10
​';
            echo $this->querylist($query, 'lod2/items/li.phtml');
        ?>
    </div>
</div>
