<?php

/**
 * OntoWiki navigation template
 *
 */

#var_dump($this->data);
?>
<p class="width98">
    <label
        class="display-block onlyAural"
        for="navigation-input">Search in Navigation</label>
    <input
        id="navigation-input"
        class="text width99 inner-label"
        type="text"
        value=""
        name="navigation-input"/>
</p>
<p id="navigation-content" class="width99 init-me-please">...</p>
