<?php

/**
 * OntoWiki navigation template
 *
 */

#var_dump($this->data);
?>
<form class="width98">
    <label
        class="display-block onlyAural"
        for="navigation-input">Search in Navigation</label>
    <input
        id="navigation-input"
        class="text width99 inner-label"
        type="text"
        value=""
        name="navigation-input"/>
</form>
<div id="navigation-content" class="width99 init-me-please">
<?php 
if( isset($this->stateView) ){
    echo $this->stateView;
} 
?>    
</div>
