<?php
/**
 * OntoWiki filter module template
 */
$odd = true;

echo "{";

$res = "";

if ($this->filter){
    $linkurl = new OntoWiki_Url(array('route' => 'properties'), array('r'));
    
    echo '"activefilters":[';
    
    foreach ($this->filter as $filter){
        if ( isset($filter['hidden'] ) && $filter['hidden'] ){
            continue;
        }
        
        // id
        $res .= '{"id":"'.$filter['id'].'",';
        
        // mode
        $res .= '"mode":"'.$filter['mode'].'",';
        
        //
        if($filter['mode'] == "box"){            
            // property
            $res .= '"property":"'.$filter['property'].'",';
            
            // link
            $res .= '"property_link":"'.(string) $linkurl->setParam('r', $filter['property'], true).'",';
            
            // label
            $res .= '"property_label":"'.$this->titleHelper->getTitle($filter['property']).'",';
            
            if ($filter['isInverse']){
                $res .= '"inverse":true,';
            }
            if ($filter['negate']){ 
                $res .= '"negate":true,';
            }
            
            $res .= '"type":"'.$filter['filter'].'",';
            if ($filter['value1']){
                if ($filter['valuetype'] == 'uri'){
                    $res .= '"value1":"'.$filter['value1'].'",';
                    $res .= '"value1_link":"'. (string) $linkurl->setParam('r', $filter['value1'], true).'",';
                    $res .= '"value1_label":"'.$this->titleHelper->getTitle($filter['value1']).'"';
                }else{
                    $res .= '"value1":"'.$filter['value1'].'"';
                }
            }
            if ($filter['value2']){
                if ($filter['valuetype'] == 'uri'){
                    $res .= ',"value2":"'.$filter['value2'].'",';
                    $res .= '"value2_link":"'.(string) $linkurl->setParam('r', $filter['value2'], true).'",';
                    $res .= '"value2_label":"'.$this->titleHelper->getTitle($filter['value2']).'"';
                }else{
                    $res .= ',"value2":"'.$filter['value2'].'"';
                }
            }
        }
        
        if($filter['mode'] == "rdfsclass"){
            $res .= '"property":"'.$filter['rdfsclass'].'",';
            $res .= '"property_link":"'.(string) $linkurl->setParam('r', $filter['rdfsclass'], true).'",';
            $res .= '"property_label":"'.$this->titleHelper->getTitle($filter['rdfsclass']).'"';
        } 
        
        if($filter['mode'] == "search"){
            $res .= '"property":"'.$filter['searchText'].'"';
        } 
        
        if($filter['mode'] == "triples"){
            $res .= '"property":"Base Query"';
        }
        
        $res .= "},";
    }
    
    echo substr($res,0,-1);
    
    echo "]";
}

echo ',"availablefilters":[';

$res = "";

foreach($this->properties as $key => $property){
    $res .= "{";
    $res .= "\"uri\":\"".$property['uri']."\","; 
    $res .= "\"title\":\"".$property["title"]."\",";
    $res .= "\"inverse\":false";
    $res .= "},";
}

foreach($this->inverseProperties as $key => $property){
    $res .= "{";
    $res .= "\"uri\":\"".$property['uri']."\","; 
    $res .= "\"title\":\"".$property["title"]."\",";
    $res .= "\"inverse\":false";
    $res .= "},";
}

echo substr($res,0,-1);

echo "]";

echo "}";
?>





