<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * OntoWiki imprint template
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

?>
<?php echo $this->notice; ?><br/><br/>
<?php echo $this->name; ?><br/>
<?php echo $this->street; ?><br/>
<?php echo $this->zip; ?> <?php echo $this->city; ?><br/>
Mail: <a href="mailto:<?php echo $this->mail; ?>"><?php echo $this->mail; ?></a><br/>


