<div id="pm-save_proceed">
    <?php if ( isset($this->patternUri) ) :  ?>
    	<a class="button" href="<?php echo $this->url(array('controller' => 'patternmanager' , 'action' => 'view')) . '?' . http_build_query(array('pattern' => $this->patternUri)); ?>">
    		<?php echo $this->_('back to detailview'); ?>
    	</a>
    	<a class="button" href="<?php echo $this->url(array('controller' => 'patternmanager' , 'action' => 'exec')) . '?' . http_build_query(array('pattern' => $this->patternUri)); ?>">
    		<?php echo $this->_('proceed to execution'); ?>
    	</a>
    <?php endif; ?>
</div>