<p>
    <span class="messagebox note">Please filter the activity stream by using the following facets:</span>
</p>
<ul class="dssn-activityfilter bullets-none separated">
    <li class="odd">By activity type:
        <ul class="inline separated">
            <li><a href="#">Share</a></li>
            <li><a href="#">Post</a></li>
            <li><a href="#">Comment</a></li>
        </ul>
    </li>
    <li>By resource type:
        <ul class="inline separated">
            <li><a href="#">Status / Note</a></li>
            <li><a href="#">Article</a></li>
            <li><a href="#">Photo</a></li>
            <li><a href="#">Video</a></li>
        </ul>
    </li>
    <li class="odd">By contact group:
        <ul class="inline separated">
            <li><a href="#">AKSW</a></li>
            <li><a href="#">OpenLink</a></li>
            <li><a href="#">Group C</a></li>
        </ul>
    </li>
    <li>By person:
        <div class="row-input">
            <label class="display-block onlyAural" for="filter-by-person">search by name</label>
            <input class="text width99 inner-label" type="text" id="filter-by-person">
        </div>
    </li>
</ul>
