<div class="row-input">
    <label class="display-block onlyAural" for="filter-by-person">Search by name or content</label>
    <input class="text width99 inner-label" type="text" id="filter-by-person">
</div>
<p>
    <span class="messagebox info">Please filter the activity stream by using the following facets:</span>
</p>
<ul class="dssn-activityfilter bullets-none separated">
    <li>
        <ul id="activityverb" class="inline separated">
            <li>Activity: <a value="all" <?php if($this->activityverb == "all"){ ?>class="selected"<?php } ?>>All</a></li>
            <li><a value="http://xmlns.notu.be/aair#Share" <?php if($this->activityverb == "http://xmlns.notu.be/aair#Share"){ ?>class="selected"<?php } ?>>Share</a></li>
            <li><a value="http://xmlns.notu.be/aair#Post" <?php if($this->activityverb == "http://xmlns.notu.be/aair#Post"){ ?>class="selected"<?php } ?>>Post</a></li>
            <li><a value="http://xmlns.notu.be/aair#Comment" <?php if($this->activityverb == "http://xmlns.notu.be/aair#Comment"){ ?>class="selected"<?php } ?>>Comment</a></li>
        </ul>
    </li>
    <li class="odd">
        <ul id="activityobject" class="inline separated">
            <li>Resource: <a value="all" <?php if($this->activityobject == "all"){ ?>class="selected"<?php } ?>>All</a></li>
            <li><a value="http://xmlns.notu.be/aair#Status" <?php if($this->activityobject == "http://xmlns.notu.be/aair#Status"){ ?>class="selected"<?php } ?>>Status / Note</a></li>
            <li><a value="http://xmlns.notu.be/aair#Site" <?php if($this->activityobject == "http://xmlns.notu.be/aair#Site"){ ?>class="selected"<?php } ?>>Article</a></li>
            <li><a value="http://xmlns.notu.be/aair#Photo" <?php if($this->activityobject == "http://xmlns.notu.be/aair#Photo"){ ?>class="selected"<?php } ?>>Photo</a></li>
            <li><a value="http://xmlns.notu.be/aair#Video" <?php if($this->activityobject == "http://xmlns.notu.be/aair#Video"){ ?>class="selected"<?php } ?>>Video</a></li>
        </ul>
    </li>
    <li>
        <ul class="inline separated">
            <li>Group: <a href="#" class="selected">All</a></li>
            <li><a href="#">AKSW</a></li>
            <li><a href="#">OpenLink</a></li>
            <li><a href="#">Group C</a></li>
        </ul>
    </li>
    <li class="odd">
        <ul class="inline separated">
            <li>Time: <a href="#" class="selected">today</a></li>
            <li><a href="#">last 7 days</a></li>
            <li><a href="#">last 30 days</a></li>
        </ul>
    </li>
    <li>
        <ul class="inline separated">
            <li>Language: <a href="#" class="selected">all</a></li>
            <li><a href="#">english</a></li>
            <li><a href="#">deutsch</a></li>
            <li><a href="#">العربية</a></li>
        </ul>
    </li>
</ul>
