<div class="row-input">
    <label class="display-block onlyAural" for="filter-by-person">Search by name or content</label>
    <input class="text width99 inner-label" type="text" id="filter-by-person">
</div>
<p>
    <span class="messagebox info">Please filter the activity stream by using the following facets:</span>
</p>
<ul class="dssn-activityfilter bullets-none separated">
    <li class="odd">
        <ul class="inline separated">
            <li>Activity: <a href"#">All</a></li>
            <li><a href="#">Share</a></li>
            <li><a href="#">Post</a></li>
            <li><a href="#">Comment</a></li>
        </ul>
    </li>
    <li>
        <ul class="inline separated">
            <li>Resource: <a href"#">All</a></li>
            <li><a href="#">Status / Note</a></li>
            <li><a href="#">Article</a></li>
            <li><a href="#">Photo</a></li>
            <li><a href="#">Video</a></li>
        </ul>
    </li>
    <li class="odd">
        <ul class="inline separated">
            <li>Group: <a href"#">All</a></li>
            <li><a href="#">AKSW</a></li>
            <li><a href="#">OpenLink</a></li>
            <li><a href="#">Group C</a></li>
        </ul>
    </li>
</ul>
