<!-- start bdays template -->

<?php if (count($this->birthdays) > 0) : ?>
    <ol class="dssn-bdays bullets-none separated">
    <?php $odd = true ?>
    <?php foreach($this->birthdays as $bday) : ?>
        <li
            title="<?php echo $bday['date'] ?>"
            class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?>">
            <a href="<?php echo $bday['resource'] ?>"> 
                <img class="avatar"  style="max-width:60px" src="<?php echo $bday['depiction'] ?>" />
                <?php echo $bday['name'] ?>
            </a> <?php echo $bday['label'] ?>
        </li>
    <?php endforeach; ?>
    </ol>
<?php else: ?>
    <p class="messagebox info">No birthdays to celebrate :-(</p>
<?php endif; ?>
<!-- end bdays template -->
