<form action="#" method="post" class="width98" id="makefriend-form">
        <div class="row-input">
            <label class="display-block onlyAural" for="makefriend-input">Add WebID or search by name</label>
            <input class="text width99 inner-label" type="text" id="makefriend-input" name="friend-input"/>
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Make Friend</button>
        </div>
</form>
