<p>
    <span class="messagebox info">Please filter your network by using the following facets:</span>
</p>
<ul class="dssn-activityfilter bullets-none separated">
    <li>
        <ul class="inline separated">
            <li>Following: <a href"#" class="selected">both</a></li>
            <li><a href="#">yes</a></li>
            <li><a href="#">no</a></li>
        </ul>
    </li>
    <li class="odd">
        <ul class="inline separated">
            <li>Relationship: <a href"#" class="selected">All</a></li>
            <li><a href="#">contact</a></li>
            <li><a href="#">friend</a></li>
            <li><a href="#">family</a></li>
            <li><a href="#">collegue</a></li>
        </ul>
    </li>
    <li>
        <ul class="inline separated">
            <li>Country: <a href"#" class="selected">All</a></li>
            <li><a href="#">Germany</a></li>
            <li><a href="#">France</a></li>
            <li><a href="#">Austria</a></li>
            <li><a href="#">unknown</a></li>
        </ul>
    </li>
    <li class="odd">
        <ul class="inline separated">
            <li>Employer: <a href"#" class="selected">All</a></li>
            <li><a href="#">University of Leipzig</a></li>
            <li><a href="#">OpenLink Software</a></li>
            <li><a href="#">Tenforce</a></li>
            <li><a href="#">Semantic Web Company</a></li>
            <li><a href="#">...</a></li>
        </ul>
    </li>
</ul>
