<form action="#" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-status">What’s happening?</label>
            <input class="text width99 inner-label" type="text" id="share-link-status" value="">
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
