<form action="<?php echo $this->data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-foto-url">Which foto you want to share?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-foto-url" id="share-foto-url" />
        </div>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-foto-comment">Your comment on this foto?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-foto-comment" id="share-foto-comment" />
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
