<form action="<?php echo $this->data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-status">What’s happening?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-status" id="share-status" />
        </div>
        <div class="actionbuttons onlyAural hidden">
            <input type="hidden" name="activity-type" value="status" />
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
<a href="<?php echo $this->urlBase."dssn/news"; ?>">Home</a>
