<form action="#" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-video-uri">Which link you want to share?</label>
            <input class="text width99 inner-label" type="text" id="share-video-uri" value="http://">
        </div>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-video-comment">You comment on this video?</label>
            <input class="text width99 inner-label" type="text" id="share-video-comment" value="">
        </div>
        <div class="actionbuttons onlyAural">
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
