<form action="#" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-uri">Which link you want to share?</label>
            <input class="text width99 inner-label" type="text" id="share-link-uri" value="http://">
        </div>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-comment">Your comment on this link?</label>
            <input class="text width99 inner-label" type="text" id="share-link-comment" value="">
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
