<form action="<?php echo $this->data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-status">What’s happening?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-link-status" id="share-link-status" />
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
