<form action="<?php echo $this->data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-video-url">Which link you want to share?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-video-url" id="share-video-url" />
        </div>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-video-comment">You comment on this video?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-video-comment" id="share-video-comment" />
        </div>
        <div class="actionbuttons onlyAural hidden">
            <input type="hidden" name="activity-type" value="video" />
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
