<form action="<?php echo $this->data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-url">Which link you want to share?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-link-url" id="share-link-url" />
        </div>
        <div class="row-input">
            <label class="display-block onlyAural" for="share-link-name">Title of this page?</label>
            <input class="dssn text width99 inner-label" type="text" name="share-link-name" id="share-link-name" />
        </div>
        <div class="actionbuttons onlyAural hidden">
            <input type="hidden" name="activity-type" value="link" />
            <button type="submit">Share it!</button>
        </div>
    </fieldset>
</form>
