<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki savedQueries module template
 *
 * @author Michael Martin
 */

?>
<?php if (!empty($this->queries)): ?>
	<ul class="bullets-none separated hierarchy">
		<?php foreach ($this->queries as $query): ?>
			<li>
			    <a class="Class ?>" href="<?php echo $query['link'] ?>" alt="<?php echo $query['description'] ?>">
					<?php echo $query['label'] ?>
				</a>
			</li>
		<?php endforeach; ?>
	</ul>
<?php else: ?>
    <p>No Queries found. Please use queryBuilding extension to create and store queries for this model.</p>
<?php endif; ?>
