<?php
// vim: sw=4:sts=4:expandtab
/**
 * OntoWiki minimap module template
 *
 * @version $Id: showproperties.phtml 4143 2009-09-08 12:26:52Z jonas.brekle $
 */

?>
<?php if ( isset($this->message) ): ?>
	<p class="messagebox info"><?php echo $this->_($this->message); ?></p>
<?php endif; ?>
<div id="miniMap" class="is-processing width99">
</div>
<script type="text/javascript">

//    $('#miniMap').addClass('is-processing');
//    $('#miniMap').addClass('width99');
//    $('#miniMap').height( $('#miniMap').width() ); 
        
    <?php
$htmlPartialUrl = new OntoWiki_Url(array('controller' => 'map', 'action' => 'inline'));
if(isset($this->context) && $this->context == 'single_instance') {
    $htmlPartialUrl->setParam('single_instance', 'on', true);
}
    ?>
    $.get('<?php echo $htmlPartialUrl; ?>', function (data) {
        $('#miniMap').removeClass('is-processing');
        $('#miniMap').html(data);
    });
</script>
