<?php
// vim: sw=4:sts=4:expandtab
/**
 * OntoWiki minimap module template
 *
 * @version $Id: showproperties.phtml 4143 2009-09-08 12:26:52Z jonas.brekle $
 */

?>
<?php if ( isset($this->message) ): ?>
	<p class="messagebox info"><?php echo $this->_($this->message); ?></p>
<?php endif; ?>
<div id="miniMap" >
    <img src="<?php echo $this->themeUrlBase; ?>images/spinner.gif"/>
</div>
<script type="text/javascript">
    <?php $htmlPartialUrl = new OntoWiki_Url(array('controller' => 'map', 'action' => 'inline'), array());//, array('r')); ?>
    $.get('<?php echo $htmlPartialUrl; ?>', function (data) {
        $('#miniMap').html(data);
    });
</script>
