<?php

/**
 * OntoWiki sync config template
 */

?>

<?php if (!isset($this->errorFlag) || $this->errorFlag === false): ?>

<script type="text/javascript">
    $(document).ready(function(){
        $("#save_btn").click(function(){
            var url = urlBase + "pubsub/subscribe?topic="+encodeURIComponent( $("#modeluri").val() );
            console.log(url);
            //$.get(
        });
    });
</script>

<fieldset>
    <div class="row-input">
        <label for="modeluri"><?php echo $this->_('Topic URL') ?></label>
        <input class="text" id="modeluri" type="text" name="topic" />
        <br class="clearall" />
    </div>
</fieldset>

<?php endif; ?>

