<?php if($this->mobile){

echo '{"values":[';

$str = "";

foreach($this->values as $value){
    $str .= "{";
    $str .= '"value":"'.$value['value'].'",';
    $str .= '"type":"'.$value['type'].'"';
    if ($value['type']=='typed-literal') {
        $str .= ',"datatype":"'.$value['datatype'].'"';
    }

    if (!empty($value['xml:lang'])) {
        $str .= ',"language":"'.$value['xml:lang'].'"';
    }
    if (isset($value['title'])){
        $str .= ',"title":"'.$value['title'].'"'; 
    }else{
        $str .= ',"title":"'.$value['value'].'"';
    }
    $str .= "},";
}

echo substr($str, 0, -1);

echo ']}';

}else{ ?>
<?php foreach($this->values as $value) : ?>
    <option
        value="<?php echo $value['value']; ?>"
        type="<?php echo $value['type']; ?>"
        <?php
            if($value['type']=='uri') {
                echo ' about="'.$value['value'].'"';
            } elseif ($value['type']=='typed-literal') {
                echo ' datatype='.$value['datatype'];
            }

            if (!empty($value['xml:lang'])) {
                echo ' language="'.$value['xml:lang'].'"';
            }
        ?>
    >
       <?php  echo isset($value['title']) ? $value['title'] : $value['value']; ?>
    </option>
<?php endforeach ?>

<?php 
    if (empty($this->values)) {
        echo 'Error: no values found';
    }
}
?>
