<?php $flag = false; ?>
<?php if ($this->has('predicates')): ?>
<?php $odd = true; $current = 0; $graphCount = count($this->graphs) ?>
<ul class="edgetoedge" about="<?php echo $this->resourceUri ?>">
    
    <?php foreach ($this->predicates as $graph => $predicatesForGraph): ?>
        <?php $current++; ?>
        <?php if (count($this->predicates[$graph]) > 0): /* has resource predicates from graph at all? */ ?>
            <?php $flag = true; ?>

        <?php foreach ($predicatesForGraph as $uri => $predicate): ?>
            <?php $currentPredicate = $this->predicates[$graph][$uri] ?>
                <li class="sep">
                    <p about="<?php echo $currentPredicate['uri'] ?>"><?php echo $currentPredicate['title'] ?></p>
                </li>
                <?php if (count($this->values[$graph][$uri]) > 1): ?>
                    <?php foreach ($this->values[$graph][$uri] as $entry): ?>
                        <li>
                                <span resource="<?php echo $entry['uri'] ?>"
                                   rel="<?php echo $currentPredicate['curi'] ?>"
                                   ><?php echo $entry['object'] ?></span>
                        </li>
                    <?php endforeach; ?>
                <?php else: ?>
                    <?php $entry = current($this->values[$graph][$uri]) ?>
                        <?php if ($entry['url']): ?>
                            <li>
                                <?php if ($entry['uri']): ?>
                                        <span rel="<?php echo $currentPredicate['curi'] ?>" resource="<?php echo $entry['uri'] ?>"
                                           ><?php echo $entry['object'] ?></span>
                                <?php else: ?>
                                        <span rel="<?php echo $currentPredicate['curi'] ?>" about="<?php echo $entry['url'] ?>"
                                           ><?php echo $entry['object'] ?></span>
                                <?php endif; ?>
                             </li>
                        <?php else: ?>
                             <li>
                                <span property="<?php echo $currentPredicate['curi'] ?>"
                                          <?php if (isset($entry['lang']) && !empty($entry['lang'])): ?>
                                                        xml:lang="<?php echo $entry['lang'] ?>"
                                                <?php elseif (isset($entry['datatype']) && !empty($entry['datatype'])): ?>
                                                  datatype="<?php echo $entry['datatype'] ?>"
                                          <?php endif; ?>
                                          >
                                          <?php echo $entry['object'] ?>
                                </span>
                             </li>
                        <?php endif; ?>
                    <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
<?php if (!$flag): ?>
    <p class="messagebox info"><?php echo $this->_('No predicates found.') ?></p>
<?php endif; ?>
