<?php

/**
 * OntoWiki properties module template
 *
 * @version $Id: properties.phtml 2335 2008-05-29 11:02:21Z norman.heino $
 */

?>
<?php if (!empty($this->properties)): ?>
	<ul class="bullets-none separated">
		<?php foreach ($this->properties as $uri => $property): ?>
		    <li>
		        <?php echo $property['title'] ?>
	            <ul class="inline separated">
	                <?php $i = 0; ?>
    		        <?php foreach ($property['values'] as $value): ?>
    		            <li <?php if (++$i == count($property['values'])) echo 'class="last-child"'?>>
        		            <?php if (!empty($value['url'])): ?>
        		                <a href="<?php echo $value['url'] ?>"><?php echo $value['object'] ?></a>
        		            <?php else: ?>
        		                <?php echo $value['object'] ?>
        		            <?php endif; ?>
    		            </li>
    		        <?php endforeach; ?>
    		    </ul>
		    </li>
		<?php endforeach; ?>
	</ul>
<?php else: ?>
	<p class="messagebox info"><?php echo $this->_($this->message) ?></p>
<?php endif; ?>
