<tr>
    <td><?php echo $this->FamilyComment ?></td>
    <td><a href="<?php echo $this->SpeciesURI ?>"><?php echo $this->SpeciesLabel ?></a> <?php echo $this->citationSuffix ?></td>
    <td class="OriginalRecordCount"><?php echo $this->OriginalRecords ?></td>
    <td class="CitedRecordCount"><?php echo $this->CitedRecords ?></td>
    <td><a href="<?php echo $this->FamilyURI ?>"><?php echo $this->FamilyLabel ?></a></td>
    <td><a href="<?php echo $this->GenusURI ?>"><?php echo $this->GenusLabel ?></a></td>
</tr>
