<tr>
    <td><?php echo $this->FamilyComment ?></td>
    <td><a href="<?php echo $this->SpeciesURI ?>"><?php echo $this->SpeciesLabel ?></a> <?php echo $this->citationSuffix ?></td>
    <td><a href="<?php echo $this->FamilyURI ?>"><?php echo $this->FamilyLabel ?></a></td>
    <td><a  class="location"
            about="<?php echo $this->LocationURI ?>"
            href="<?php echo $this->LocationURI ?>"><span class="name"><?php echo $this->querylist_titleHelper->getTitle($this->LocationURI) ?></span>
            <span class="lat" style="display: none"><?php echo $this->lat ?></span>
            <span class="long" style="display: none"><?php echo $this->long ?></span>
        </a>
    </td>
    <?php if (isset($this->RecordLabel)) :?>
    <td><a href="<?php echo $this->RecordURI ?>"><?php echo $this->RecordLabel ?></a></td>
    <?php else: ?>
    <td></td>
    <?php endif; ?>
    <td>
        <?php if ($this->RecordType == 'http://purl.org/net/faunistics#OriginalRecord') :?>
        Original
        <?php elseif ($this->RecordType == 'http://purl.org/net/faunistics#CitedRecord') :?>
        Cited
        <?php else: ?>
        Unknown
        <?php endif; ?>
    </td>
</tr>
