<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper
);


?>
<div class="box">
    <h2 class="taxon">
        <?php
        echo '<strong>' . $this->title . '</strong>';
        if (isset($this->description['http://purl.org/net/faunistics#citationSuffix'])) {
            $suffix = $this->description['http://purl.org/net/faunistics#citationSuffix'][0]['value'];
            echo ' ' . $suffix;
        }
        ?>
    </h2>
    <div class="block">
<div class="article first">
    <?php echo $this->partial('spiders/content.phtml', $templateData); ?>

<?php
$rdfsComment = 'http://www.w3.org/2000/01/rdf-schema#comment';
if (isset($this->description[$rdfsComment])) {
    $comment = $this->description[$rdfsComment][0]['value'];
    echo '<p><strong>Comments:</strong> '.$comment.'</p>';
}
?>

<p class="meta">
<?php
$model = OntoWiki::getInstance()->selectedModel;
$subTaxonOf = 'http://purl.org/net/faunistics#subTaxonOf';
$closure = Erfurt_App::getInstance()->getStore()->getTransitiveClosure((string) $model, $subTaxonOf, $this->resourceUri, false);
$titleHelper = new OntoWiki_Model_TitleHelper($model);
echo 'Taxa: ';
$taxon = $closure[$this->resourceUri];
while (isset($taxon['parent'])) {
    $titleHelper->addResource( $taxon['parent'] );
    if (isset($closure[$taxon['parent']])) {
        $taxon = $closure[$taxon['parent']];
    } else {
        $taxon = null;
    }
}
$taxon = $closure[$this->resourceUri];
$first = true;
while (isset($taxon['parent'])) {
    $title = $titleHelper->getTitle( $taxon['parent'] );
    if ($first == false) {
        echo ' &lt;&lt; ';
    }
    echo "<a href='$taxon[parent]'>$title</a>";
    $first = false;
    if (isset($closure[$taxon['parent']])) {
        $taxon = $closure[$taxon['parent']];
    } else {
        $taxon = null;
    }
}
echo "<br/>";
#var_dump($closure);

$euroSpidersID = 'http://purl.org/net/faunistics#euroSpidersID';
if (isset($this->description[$euroSpidersID])) {
    $theId = $this->description[$euroSpidersID][0]['value'];
    echo 'External Links: <a href="http://www.araneae.unibe.ch/datasheet.php?spec=' . $theId . '">araneae - Spiders of Europe</a> (determination)</br>';
}
?>                
</p>

    </div>
    </div>
</div>
<div class="box">
    <h2>Map</h2>
    <div class="block">
        <div class="speciesmap">...</div>
    </div>
</div>

<?php

$queryObject = new Erfurt_Sparql_SimpleQuery();
$queryObject->setProloguePart('
PREFIX faun: <http://purl.org/net/faunistics#>
PREFIX geof: <http://www.mindswap.org/2003/owl/geo/geoFeatures.owl#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?RecordURI ?RecordLabel ?PublicationUri ?PublicationLabel ?SourceURI ?SourceLabel ?LocationURI ?lat ?long
    ');

$queryObject->setWherePart('
WHERE
{
  ?RecordURI faun:identifiesAs <'.$this->resourceUri.'>.
  ?RecordURI a <http://purl.org/net/faunistics#OriginalRecord>.
  OPTIONAL {
    ?RecordURI rdfs:label ?RecordLabel.
  }
  ?RecordURI faun:publishedIn ?PublicationUri.
  ?PublicationUri rdfs:label ?PublicationLabel.
  OPTIONAL {
    ?RecordURI faun:citedIn ?SourceURI.
    ?SourceURI rdfs:label ?SourceLabel.
  }

  {
  ?RecordURI faun:recordedAtLocation <http://db.caucasus-spiders.info/Area/152> .
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within <http://db.caucasus-spiders.info/Area/152>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within <http://db.caucasus-spiders.info/Area/152>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within ?l2.
  ?l2 geof:within <http://db.caucasus-spiders.info/Area/152>.
  }

  OPTIONAL {
    ?LocationURI geo:lat ?lat.
    ?LocationURI geo:long ?long.
  }
}
    ');

$queryObject->setLimit('10000');
?>

<div class="box">
    <h2>Records</h2>
    <div class="block">
        <table class="checklist">
            <thead>
                <tr>
                    <th>Publication</th>
                    <th>Location</th>
                    <th>Record / Label</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->querylist($queryObject, 'spiders/types/species-row-original.phtml'); ?>
            </tbody>
        </table>
        <p style="display: none">
            <?php echo htmlentities( (string) $queryObject) ?>
        </p>
    </div>
</div>


<?php

$queryObject = new Erfurt_Sparql_SimpleQuery();
$queryObject->setProloguePart('
PREFIX faun: <http://purl.org/net/faunistics#>
PREFIX geof: <http://www.mindswap.org/2003/owl/geo/geoFeatures.owl#>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?RecordURI ?RecordLabel ?PublicationUri ?PublicationLabel ?SourceURI ?SourceLabel ?LocationURI ?lat ?long
    ');

$queryObject->setWherePart('
WHERE
{
  ?RecordURI faun:identifiesAs <'.$this->resourceUri.'>.
  ?RecordURI a <http://purl.org/net/faunistics#CitedRecord>.
  OPTIONAL {
    ?RecordURI rdfs:label ?RecordLabel.
  }
  ?RecordURI faun:publishedIn ?PublicationUri.
  ?PublicationUri rdfs:label ?PublicationLabel.
  OPTIONAL {
    ?RecordURI faun:citedIn ?SourceURI.
    ?SourceURI rdfs:label ?SourceLabel.
  }

  {
  ?RecordURI faun:recordedAtLocation <http://db.caucasus-spiders.info/Area/152> .
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within <http://db.caucasus-spiders.info/Area/152>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within <http://db.caucasus-spiders.info/Area/152>.
  }
  UNION
  {
  ?RecordURI faun:recordedAtLocation ?LocationURI .
  ?LocationURI geof:within ?l1.
  ?l1 geof:within ?l2.
  ?l2 geof:within <http://db.caucasus-spiders.info/Area/152>.
  }

  OPTIONAL {
    ?LocationURI geo:lat ?lat.
    ?LocationURI geo:long ?long.
  }
}
    ');

$queryObject->setLimit('10000');

?>

<div class="box">
    <h2>References to Records</h2>
    <div class="block">
        <table class="checklist">
            <thead>
                <tr>
                    <th>Publication</th>
                    <th>Location</th>
                    <th>Source</th>
                    <th>Record / Label</th>
                </tr>
            </thead>
            <tbody>
                <?php echo $this->querylist($queryObject, 'spiders/types/species-row-cited.phtml'); ?>
            </tbody>
        </table>
        <p style="display: none">
            <?php echo htmlentities( (string) $queryObject) ?>
        </p>
    </div>
</div>
