<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2006-2013, {@link http://aksw.org AKSW}
 * @license   http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki lastcomments module template
 *
 * @author     Sebastian Tramp <tramp@informatik.uni-leipzig.de>
 * @author     Natanael Arndt <arndtn@gmail.com>
 */
?>
<?php if ($this->has('infomessage')): ?>
    <p class="messagebox info"><?php echo $this->_($this->infomessage) ?></p>
<?php endif?>

<?php if ($this->has('comments')): ?>
<div id="comment-list">
<?php echo $this->comments; ?>
</div>

<?php if ($this->has('more')): ?>
    <p class="messagebox info">There are more comments out there ...</p>
<?php endif?>

<?php endif?>
