<?php
/**
 * OntoWiki lastcomments module template
 *
 * @author     Sebastian Dietzold <dietzold@informatik.uni-leipzig.de>
 * @copyright  Copyright (c) 2009, {@link http://aksw.org AKSW}
 * @license    http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 * @version    $Id: lastcomments.phtml 3575 2009-07-05 15:00:22Z sebastian.dietzold $
 */
?>
<?php if ($this->has('infomessage')): ?>
    <p class="messagebox info"><?php echo $this->infomessage ?></p>
<?php endif?>

<?php if ($this->has('comments')): ?>
<table class="separated-vertical">
<?php
    $odd = false;
    foreach($this->comments as $comment){
        echo $this->partial('partials/list_community_item.phtml',
            array(
                'author'        => $comment['author'],
                'comment'       => $comment['comment'],
                'commentUrl'    => $comment['comment'],
                'resource'      => $comment['resource'],
                'resourceUrl'   => $this->urlBase . 'community/list/?r=' . urlencode($comment['resource']),
                'resourceName'  => $comment['rname'],
                'content'       => $comment['content'],
                'date'          => $comment['date'],
                'odd'           => $odd,
            )
        );
        $odd = !$odd;
    }
?>
</table>

<?php if ($this->has('more')): ?>
    <p class="messagebox info">There are more comments out there ...</p>
<?php endif?>

<?php endif?>
