<?php 
	if ( empty($this->listData) ) { ?>
    <p class="messagebox info"><?php echo $this->_('No queries saved yet.'); ?> </p>
<?php } else { 
	$this->headScript()->appendScript('$(document).ready(function(){
		$(".delquery").click(function(){ var thisrow = $(this).parent().parent(); var uri = $(this).attr("uri");
			$.ajax({
				  url: "'.$this->urlBase."querybuilding/delete".'",
				  type: "POST",
			      data: ({
					"uri": uri
				  }),
			      dataType: "text",
			      success: function(msg){
			         //TODO check for status
                                 if(msg != "All OK"){
                                    alert("Fehler "+msg);
                                 } else {
                                    thisrow.remove();
                                 }
			      }
				});
		})
	})');
	?>
    <table class="separated-vertical">
        <thead><tr>
            <th><?php echo $this->_('name'); ?></th>
            <th><?php echo $this->_('description'); ?></th>
            <th><?php echo $this->_('creator'); ?></th>
            <th><?php echo $this->_('date'); ?></th>
            <th><?php echo $this->_('open'); ?></th>
            <th><?php echo $this->_('del'); ?></th>
        </tr></thead>
        <tbody>

        <?php $evenOdd = 'even'; ?>
        <?php foreach ($this->listData as $entry) { ?>
            <?php $evenOdd = ($evenOdd === 'even') ? 'odd' : 'even'; ?>  
            <tr class="<?php echo $evenOdd; ?>">
                <td><?php echo $entry['name']; ?></td>
                <td><?php echo $entry['desc']; ?></td>
                <td><?php echo OntoWiki_Utils::getUriLocalPart($entry['creator']); ?></td>
                <td><?php 
	                if (($timestamp = strtotime($entry['date'])) === false) {
					    echo "Die Zeichenkette ($str) ist nicht parsebar.";
					} else {
					    echo date('d.m.Y H:i:s', $timestamp);
					} ?>
				</td>
				<td>
					<?php 
						if($entry['generator']=="qb"){
							$base = $this->urlBase."querybuilder/manage";
							$base .= "?patterns=".htmlentities($entry['json']);
							$base .= "&label = ".$entry['name'];
						} elseif ($entry['generator']=="gqb"){
							$base = $this->urlBase."graphicalquerybuilder/display?open=true";
							$base .= "&queryuri=".htmlentities($entry['query']);
						}
					$qelink = $this->urlBase."model/query?immediate=1&query=".urlencode($entry['sparql']);
                                        ?>
					<a style="margin:2px;" class="minibutton" href="<?php echo $qelink; ?>">qe</a>
                                        <?php if($entry['generator']=="qb" || $entry['generator']=="gqb"){?>
                                            &nbsp;<a style="margin:2px;" class="minibutton" href="<?php echo $base;?>">
                                                <?php echo $entry['generator']; ?>
                                            </a><?php
                                        } ?>
					<!--Only uncomment line below if it is working-->
                    <!--<form action="<?php echo $this->_config->urlBase; ?>" method="post">
                        <input type="hidden" name="patterns" value="<?php echo htmlentities($entry['sioc:content']); ?>">
                    <a class="minibutton submit"> submit </a>
                    </form>-->
                </td>
                <td><a class="delquery minibutton" style="margin:2px;color:red;" uri="<?php echo htmlentities($entry['query']); ?>">x</a></td>
            </tr>
        <?php } ?>

        </tbody>
    </table>
<?php } ?>
