<?php $odd = true;
    if ($this->instances->hasData()): ?>
<ul class="resource-list seperated-vertical"
    <?php foreach ($this->instanceInfo as $instanceUri => $instance){
            echo $this->partial('partials/list_extensions_element.phtml',
                array(
                    'instanceUri'  => $instanceUri,
                    'instance'     => $instance,
                    'instanceData' => $this->instanceData,
                    'instanceInfo' => $this->instanceInfo,
                    'propertyInfo' => $this->propertyInfo,
                    'other'        => $this->other,
                    'odd'          => $odd
                )
             );
            $odd = !$odd;
        } ?>
</ul>
    <?php else: ?>
<p class="messagebox info"><?php echo $this->_('No matches.') ?></p>
    <?php endif; ?>


