<li class="<?php echo $this->odd ? 'odd' : 'even'; ?>">
    <?php if($this->instance['type'] == 'uri'){       
        if(isset($this->instanceData[$this->instanceUri]['name'])){
            $name = $this->instanceData[$this->instanceUri]['name'][0]['origvalue'];
        } else {
            $name =  $this->instanceUri; //TODO title helper
        }
        
        if(isset($this->instanceData[$this->instanceUri]['title'])){
            $title = $this->instanceData[$this->instanceUri]['title'][0]['value'];
        }  else {
            $title = $name;
        }
        
        if(isset($this->instanceData[$this->instanceUri]['description'])){
            $description = $this->instanceData[$this->instanceUri]['description'][0]['value'];
        } else {
            $description =  'no description';
        }
        
        if(isset($this->instanceData[$this->instanceUri]['author'])){
            $author = $this->instanceData[$this->instanceUri]['author'][0]['url'];
        } else {
            $author =  null;
        }
        
        if(isset($this->instanceData[$this->instanceUri]['authorlabel'])){
            $authorLabel = $this->instanceData[$this->instanceUri]['authorlabel'][0]['value'];
        } else {
            $authorLabel =  'unknown author';
        }
        
        if (isset($this->instanceData[$this->instanceUri]['latestReleaseLocation'])) {
            $location = $this->instanceData[$this->instanceUri]['latestReleaseLocation'][0]['uri'];
        } else {
            if(strpos($this->instanceUri, 'https://github.com/AKSW') === 0){
                $location = implode('/', array_slice(explode('/', $this->instanceUri), 0, 5)) . '/zipball/master';
            } else {
                $location = null;
            }
        }

?>
            <div class="extension has-contextmenu-area" id="<?php echo $name; ?>">
                <h3><span class="name"><?php echo $title ?></span></h3>
                <span class="author">by <?php if($author !== null){?><a href="<?php echo $author;?>"><?php echo $authorLabel;?></a> <?php } else echo $authorLabel;?></span>
            <p class="description"><?php echo $description; ?></p>
            <?php
            if($location !== null){
                $url = new OntoWiki_Url(array('controller' => 'exconf', 'action'=>'installarchiveremote'));
                $url->url = $location;
                $url->name = $name;
                $action = false;
                if(!$this->installed){
                    $label = 'install';
                    $action = true;
                } else if($this->updateable){
                    $label = 'update';
                    $action = true;
                }
                if($action){
                ?>
                <a class="minibutton button install" href="<?php echo $url; ?>"><?php echo $label; ?></a>
                <?php
                } else {
                  ?>
                <p class="info">installed and updated</p>
                <?php
                }
            } else {
                ?>
                <p class="info">missing release link</p>
                <?php
            }
        }
        ?>
        </div>
    </li>
