<li class="<?php echo $this->odd ? 'odd' : 'even'; ?>">
    <?php if($this->instance['type'] == 'uri'){ ?>
            <a class="hasMenu expandable"
               about="<?php echo $this->instanceUri ?>"
                           <?php if(isset($this->instanceData[$this->instanceUri]['__TYPE'])) : ?>
               typeof="<?php echo $this->curie($this->instanceData[$this->instanceUri]['__TYPE'][0]['value']) ?>"
                               <?php endif; ?>
               href="<?php echo $this->instance['url']?>">
                        <?php echo $this->instance['title'] ?>
            </a>
            <br />
                        <?php if (isset($this->instanceData[$this->instanceUri]) && isset($this->instanceData[$this->instanceUri]['__TYPE'])): ?>
                            <?php if (count($this->instanceData[$this->instanceUri]['__TYPE']) > 1): ?>
                                <?php $j = 0;
                                $count = count($this->instanceData[$this->instanceUri]['__TYPE']) ?>
                                <?php foreach ($this->instanceData[$this->instanceUri]['__TYPE'] as $type): ?>
                                    <?php echo $type['value'] . ($count > ++$j ? ', ' : '') ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <?php echo $this->instanceData[$this->instanceUri]['__TYPE'][0]['value'] ?>
                            <?php endif; ?>
                        <?php endif; ?>
            <?php } else { ?>
                <?php echo $this->instance['title'] ?><br/>
                Literal
            <?php } ?>
        
    </li>