<?php $odd = true;

if ($this->instances->hasData()): ?>
<ol class="bullets-none separated">
    <?php foreach ($this->instanceInfo as $instance){
            echo $this->partial('partials/list_extensions_element.phtml',
                array(
                    'instanceUri'  => $instance['uri'],
                    'instance'     => $instance,
                    'instanceData' => $this->instanceData,
                    'instanceInfo' => $this->instanceInfo,
                    'propertyInfo' => $this->propertyInfo,
                    'odd'          => $odd
                )
             );
            $odd = !$odd;
        } ?>
</ol>
    <?php else: ?>
<p class="messagebox info"><?php echo $this->_('No extensions found.') ?></p>
    <?php endif; ?>


