<?php
$url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
$url->setParam('r', $this->resourceUri, true);
$abstract = '';
if (isset($this->description['http://lod2.eu/schema/abstract'])) {
    $abstract = '<p>'.$this->description['http://lod2.eu/schema/abstract'][0]['value'].'</p>';
}
?>

<div class="article">
    <h3><a href="<?php echo $url ?>"><?php echo $this->title ?></a></h3>
    <?php echo $abstract ?>
</div>