<?php $data = $this->data ?>
<form action="<?php echo $data->formUrl ?>" method="post" class="width98">
    <fieldset>
        <div class="row-input">
            <label class="display-block onlyAural" for="manchester">Describe this resource in manchester syntax ...</label>
            <input class="text width99 inner-label" style="height: 5em" type="text" name="manchester" id="manchester" value="<?php echo $data->manchesterString?>"/>
        </div>
        <div class="actionbuttons onlyAural hidden">
            <button type="submit">Save</button>
        </div>
    </fieldset>
</form>

