<?php
// this is the standard template data
$templateData = array(
                'title' => $this->title,
                'resourceUri' => $this->resourceUri,
                'description' => $this->description,
                'descriptionHelper' => $this->descriptionHelper,
                'options'           => $this->options
        );
?>
<div class="box">
    <h2>
        <?php echo $this->title ?>
    </h2>
    <div class="block">
        <div class="project article first">
            <?php echo $this->partial( 'lod2/content.phtml', $templateData); ?>
            <p class="meta">
                <?php echo $this->partial( 'lod2/lastchange.phtml', $this->lastchange($this->resourceUri)); ?>
            </p>
        </div>
    </div>
</div>
