<?php 
$login_url = $this->login_url;
$message = $this->message;
echo $message;
?>
<div class="qiufeng">
	<div class="login_title">Login	</div>
	<div class="login_border">  	
	  	<form name="login_form" id="login_form" method="post" action="<?php echo $login_url;?>">
		  <div class="login_line_first">Username: <input type="text" name="username" id="username" class="login_username" /></div>
		  <div class="login_line">Password: <input type="password" name="password" id="password" class="login_password" /></div>
		  <div class="login_line"><br /></div>
		  <div class="login_line"><hr width="100" align="left" color="#999999" noshade="noshade"/></div>
		  <div class="login_line"><button type="submit" name="login" onclick=""><?php echo $this->_('Login') ?></button></div>
		</form>
	</div>
</div>