
default:

prepare:
	rm -rf ../../build*
	rm -f ../../Makefile
	rm -f ../../web.config
	rm -rf ../../libraries/Erfurt
	rm -rf ../../libraries/RDFauthor
	rm -f ../../extensions/themes/silverblue/scripts/libraries/jquery.js
	rm -f ../../extensions/exconf/pclzip.lib.php
	rm -rf ../../extensions/markdown/parser
	rm -f ../../extensions/queries/resources/codemirror/LICENSE

clean:
	rm -rf ../*.log
	rm -rf ../ontowiki-common
	rm -rf ../ontowiki-mysql
	rm -rf ../ontowiki-virtuoso
	rm -rf ../files
	rm -rf ../*.substvars

package:

