
default:

prepare:
	rm -rf ../../build*
	rm -rf ../../Makefile
	rm -rf ../../web.config
	rm -rf ../../libraries/Erfurt
	rm -rf ../../libraries/RDFauthor
	rm -rf ../../extensions/themes/silverblue/scripts/libraries/jquery.js
	rm -rf ../../extensions/exconf/pclzip.lib.php
	rm -rf ../../extensions/markdown/parser/markdown.php

clean:
	rm -rf ../*.log
	rm -rf ../ontowiki-common
	rm -rf ../ontowiki-mysql
	rm -rf ../ontowiki-virtuoso
	rm -rf ../files
	rm -rf ../*.substvars

package:

