<?php
$start = microtime(true);
$instances = $this->instances;

// build menu
$actionMenu = new OntoWiki_Menu();
$actionMenu->setEntry('Toggle show Permalink', "javascript:showPermaLink()");
$actionMenu->setEntry('Toggle show Resource Query',"javascript:showresQuery()");
$actionMenu->setEntry('Toggle show Value Query', "javascript:showvalQuery()");
$actions = new OntoWiki_Menu();
$actions->setEntry('View', $actionMenu);
$this->placeholder('main.window.menu')->set($actions->toArray());

// get queries
$resourceQuery =  $instances->getResourceQuery();
//echo htmlentities($resourceQuery);
$valueQuery = $instances->getQuery();
//echo htmlentities($valueQuery);
$config = Erfurt_App::getInstance()->getConfig();
$permalink = $instances->getPermalink($this->listName);

$graph = $this->instances->getGraph();
$store = $this->instances->getStore();

// prepare namespaces
try{
    $namespaces = $graph->getNamespaces();
} catch (Exception $e){
    $namespaces = array();
}
$graphBase  = $graph->getBaseUri();
if (!array_key_exists($graphBase, $namespaces)) {
    $namespaces = array_merge($namespaces, array($graphBase => OntoWiki_Utils::DEFAULT_BASE));
}

//data for filter module
$filter = $instances->getFilter();
$filter_js = json_encode(is_array($filter) ? $filter : array());

$this->headScript()->prependFile(
        OntoWiki::getInstance()->extensionManager->getComponentUrl('filter') .'resources/FilterAPI.js'
);
$this->headScript()->prependScript(
        'function showPermaLink(){$("#permalink").slideToggle(400);}
            function showresQuery(){$("#resQuery").slideToggle(400);}
            function showvalQuery(){$("#valQuery").slideToggle(400);}
             var reloadUrl = "'.
        new OntoWiki_Url(array()). // url to reload -> without config params
        '";
            var filtersFromSession = ' . $filter_js.';
            var listName = "'.$this->listName.'";'
        );

if ($instances->hasData()) {
    $instanceInfo = $instances->getResources();
    $instanceData = $instances->getValues();
    //echo '<pre>'; print_r($instanceData); echo '</pre>';
    
    $itemsOnPage = count($instanceData);
    
    $propertyInfo = $instances->getShownProperties();
    
    $time = (microtime(true) - $start) * 1000;
    
    $start     = $instances->getOffset() + 1;
    $translate = OntoWiki::getInstance()->translate;
    
    $statusBar = $this->placeholder('main.window.statusbar');
    
    $limit = $instances->getLimit();
    $offset = $instances->getOffset();
    if($limit != 0) {
        $page = ($offset / $limit) +1;
    } else {
        $page = 1;
    }
    
    if($graph->getOption($config->sysont->properties->isLarge)) {
        $statusBar->append(OntoWiki_Pager::get( Erfurt_Store::COUNT_NOT_SUPPORTED, $limit, $itemsOnPage, $page, $this->listName));
    } else {
        $query = clone $instances->getResourceQuery();
        
        $where = 'WHERE '.$query->getWhere();
        
        try {
            $count = $store->countWhereMatches($graph->getModelIri(), $where, '?resourceUri', true);
        } catch (Erfurt_Store_Exception $e) {
            $count = Erfurt_Store::COUNT_NOT_SUPPORTED;
        }
        $statusBar->append(OntoWiki_Pager::get($count, $limit, $itemsOnPage, $page, $this->listName));
        
        if ($count != Erfurt_Store::COUNT_NOT_SUPPORTED) {
            $results = $count > 1 ? $translate->translate('results') : $translate->translate('result');
            $numResultsMsg = sprintf($translate->translate('Search returned %1$d %2$s.'), $count, $results);
            $statusBar->append(sprintf($translate->translate('Search returned %1$d %2$s.'), $count, $results));
        }
    }
    $thisActionUrl = new OntoWiki_Url().'/';
    $limit = '<ul><li>Show me: <a class="minibutton" href="'. $thisActionUrl.'list/'.$this->listName.'/limit/10'.'">10</a></li>';
    $limit .= '<li><a class="minibutton" href="'. $thisActionUrl.'list/'.$this->listName.'/limit/50'.'">50</a></li>';
    $limit .= '<li><a class="minibutton" href="'. $thisActionUrl.'list/'.$this->listName.'/limit/100'.'">100</a></li>';
    $limit .= '<li> ... <a class="minibutton" href="'. $thisActionUrl.'list/'.$this->listName.'/limit/0'.'">all</a></ul></li>';
    $statusBar->append($limit);
    
    if (defined('_OWDEBUG')) {
        $timeMsg = sprintf($translate->translate('Query execution took %1$d ms.'), $time);
        $statusBar->append(sprintf($translate->translate('Query execution took %1$d ms.'), $time));
    }
} else {
    $instanceData = array();
    $instanceInfo = array();
    $propertyInfo = array();
}
$url = new OntoWiki_Url(array('controller' => 'resource','action' => 'instances'));$url->setParam('init', true);
?>
<div id="permalink" class="messagebox" style="display:none"><?php echo $permalink; ?></div>
<div id="resQuery" class="messagebox" style="display:none"><?php echo htmlentities($resourceQuery); ?><br><a href="<?php echo $config->urlBase; ?>queries/editor/?query=<?php echo urlencode($resourceQuery)?>">Open in editor</a></div>
<div id="valQuery" class="messagebox" style="display:none"><?php echo htmlentities($valueQuery); ?><br><a href="<?php echo $config->urlBase; ?>queries/editor/?query=<?php echo urlencode($valueQuery)?>">Open in editor</a></div>

<?php
//other contains template specific data
$other = new stdClass();
$other->namespaces =$namespaces;
$other->graphbase = $graphBase;

//call the requested template
echo $this->partial('partials/'.$this->mainTemplate.'.phtml',
                array(
                    'instances'    => $instances,
                    'instanceData' => $instanceData,
                    'instanceInfo' => $instanceInfo,
                    'propertyInfo' => $propertyInfo,
                    'other'        => $other,
                    'elementTemplate' => $this->elementTemplate,
                    'start'        => $start
                )
             );
?>
