<?php

$instances = $this->instances;

$graph = $this->instances->getGraph();
$store = $this->instances->getStore();

$config = Erfurt_App::getInstance()->getConfig();

$statusBar = '';

if ($instances->hasData()) {
    $instanceInfo = $instances->getResources();
    $instanceData = $instances->getValues();
    
    $itemsOnPage = count($instanceData);
    
    $propertyInfo = $instances->getShownProperties();
    
    $start     = $instances->getOffset() + 1;
    $translate = OntoWiki::getInstance()->translate;
    
    $limit = $instances->getLimit();
    $offset = $instances->getOffset();
    if($limit != 0) {
        $page = ($offset / $limit) +1;
    } else {
        $page = 1;
    }

    if($graph->getOption($config->sysont->properties->isLarge)) {
        $statusBar = OntoWiki_Pager::get( Erfurt_Store::COUNT_NOT_SUPPORTED, $limit, $itemsOnPage, $page, $this->listName);
    } else {
        $query = clone $instances->getResourceQuery();

        $where = 'WHERE '.$query->getWhere();

        try {
            $count = $store->countWhereMatches($graph->getModelIri(), $where, '?resourceUri', true);
        } catch (Erfurt_Store_Exception $e) {
            $count = Erfurt_Store::COUNT_NOT_SUPPORTED;
        }
        $statusBar = OntoWiki_Pager::get($count, $limit, $itemsOnPage, $page, $this->listName);
    }
    $statusBar = str_replace("<ul>",'', $statusBar);
    $statusBar = str_replace("First",'', $statusBar);
    $statusBar = str_replace("Previous",'', $statusBar);
    $statusBar = str_replace("Last",'', $statusBar);
    $statusBar = str_replace("Next",'', $statusBar);
    $statusBar = str_replace("<li>",'<p class="pager">', $statusBar);
    $statusBar = str_replace("</li>",'</p>', $statusBar);
    $statusBar = preg_replace('/href="(.+?)"/i','href="#" about="$1" onclick="pageList(this);"', $statusBar);
}

$odd = true;
if ($instances->hasData()):
?>
    <ul class="rounded">
        <?php foreach ($instanceInfo as $instanceUri => $instance): ?>
            <li>
                <!-- <?php echo  $instanceUri?> -->
                <a about="<?php echo $instance['url'] ?>" href="#" onclick="onInstanceClick(this); return false;">
                    <?php echo $instance['title'] ?>
                </a>
                <?php if (isset($instanceData[$instanceUri]) && isset($instanceData[$instanceUri]['__TYPE'])): ?>
                    <small class="counter">
                    <?php if (count($instanceData[$instanceUri]['__TYPE']) > 1): ?>
                        <?php $j = 0;
                        $count = count($instanceData[$instanceUri]['__TYPE']) ?>
                        <?php foreach ($instanceData[$instanceUri]['__TYPE'] as $type): ?>
                            <?php echo $type['value'] . ($count > ++$j ? ', ' : '') ?>
                        <?php endforeach; ?>
                    <?php else: ?>
                        <?php echo $instanceData[$instanceUri]['__TYPE'][0]['value'] ?>
                    <?php endif; ?>
                    </small>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php echo $statusBar; ?>

    <?php else: ?>
        <p class="messagebox info"><?php echo $this->_('No matches.') ?></p>
    <?php endif; ?>