<p class="messagebox info"><?php echo $this->_('If you think your query can be useful for others, please share it.') ?></p>
<p>
<input type="text" class="text width98 inner-label"  id="qname" value="<?php echo $this->_('name of query') ?>" maxlength="20" />
</p><p>
<textarea  class="text width99 inner-label" style="min-width: 50%; min-height: 4.5em;" id="qdesc"><?php echo $this->_('description of the query') ?></textarea>
<!--br/>Share: <input id="savequerysharecheckbox" type="checkbox"  value="checked" checked="checked"/-->
<input id="hidden_query" type="hidden"  value=""/><input id="hidden_json" type="hidden" value=""/>  
</p>

<a id = 'savequerybutton' class="button submit"><span><?php echo $this->_('Save Query'); ?></span></a>