<h3><?php echo $this->resourceName ?>'s vCard</h3>
<div class="nsWrapper" about="<?php echo $this->resourceUri ?>"
     <?php foreach ($this->namespaces as $namespace => $prefix): ?>
         <?php echo ' xmlns:' . $prefix . '="' . $namespace . '"' ?>
     <?php endforeach; ?>
     typeof="foaf:Person">
     
     <div class="vcard">
         <span class="fdepiction" rel="<?php echo $this->curie($this->uris['depiction']) ?>" resource="<?php echo $this->depiction[0]['value'] ?>">
             <?php if (isset($this->depiction)): ?>
                 <img class="fdepiction" src="<?php echo $this->depiction[0]['value'] ?>" alt="depiction of <?php echo $this->resourceName ?>">
             <?php endif; ?>
         </span>
         <div class="properties">

             <?php if (isset($this->title)): ?>
                 <span class="ftitle block" property="<?php echo $this->curie($this->uris['title']) ?>"><?php echo $this->title[0]['value'] ?></span>
             <?php endif; ?>

             <span class="block fname">
                 <?php if (isset($this->name)): ?>
                     <span property="<?php echo $this->curie($this->uris['name']) ?>"><?php echo $this->name[0]['value'] ?></span>
                 <?php else: ?>
                     <?php if (isset($this->firstName)): ?>
                         <span property="<?php echo $this->curie($this->uris['firstName']) ?>"><?php echo $this->firstName[0]['value'] ?></span>
                     <?php endif; ?>

                     <?php if (isset($this->surname)): ?>
                         <span property="<?php echo $this->curie($this->uris['surname']) ?>"><?php echo $this->surname[0]['value'] ?></span>
                     <?php elseif (isset($this->familyName)): ?>
                         <span property="<?php echo $this->curie($this->uris['familyName']) ?>"><?php echo $this->familyName[0]['value'] ?></span>
                     <?php endif; ?>
                 <?php endif; ?>

                 <?php if (isset($this->nick)): ?>
                     <span class="fnick" property="<?php echo $this->curie($this->uris['nick']) ?>"><?php echo $this->nick[0]['value'] ?></span>
                 <?php elseif (isset($this->givenName)): ?>
                     <span class="fnick" property="<?php echo $this->curie($this->uris['givenName']) ?>"><?php echo $this->givenName[0]['value'] ?></span>
                 <?php endif; ?>
             </span>

             <?php if (isset($this->mbox)): ?>
                 <span class="fmbox block" rel="<?php echo $this->curie($this->uris['mbox']) ?>" resource="<?php echo $this->mbox[0]['value'] ?>">
                   <a href="<?php echo $this->mbox[0]['value'] ?>"><?php echo str_replace('mailto:', '', $this->mbox[0]['value']) ?></a>
                 </span>
             <?php endif; ?>
       </div>
     </div>

     <?php if (isset($this->knows)): ?>
         <h3><?php echo $this->resourceName ?>'s Acquaintances</h3>
         <ul rel="<?php echo $this->curie($this->uris['knows']) ?>">
         <?php foreach ($this->knows as $known): ?>
             <li resource="<?php echo $known['value'] ?>"><?php echo $known['value'] ?></li>
         <?php endforeach; ?>
         </ul>
     <?php endif; ?>

     <?php if (isset($this->workplaceHomepage) || isset($this->workinfoHomepage) || isset($this->schoolHomepage)|| isset($this->weblog)): ?>
         <h3><?php echo $this->resourceName ?>'s Resources</h3>
     <?php endif; ?>

     <?php if (isset($this->topicInterest)): ?>
         <h3><?php echo $this->resourceName ?>'s Interests</h3>
     <?php endif; ?>

     <?php if (isset($this->basedNear)): ?>
         <h3><?php echo $this->resourceName ?>'s Location</h3>
     <?php endif; ?>
</div>
