<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2012, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * OntoWiki application module template
 *
 * @version $Id$
 */

?>

<form method="GET" action="<?php echo $this->actionUrl ?>">
	<?php if ($this->showSearch) : ?>
	<p class="width98">
		<label class="display-block" for="searchtext-input"><?php echo $this->_('Search for Resources') ?></label>
		<input class="text width99 inner-label" type="text" id="searchtext-input" name="searchtext-input" value="<?php echo $this->searchtextinput ?>" />
	</p>
	<?php endif; ?>
	<p>
		<!--label class="display-block">
		    <?php $selected = ($this->modelSelected ? '' : 'checked="checked"') ?>
			<input class="checkbox" type="checkbox" name="allModels" id="allModels" <?php echo $selected ?>/>
			<?php echo $this->_('Search all Knowledge Bases') ?>
		</label-->
		<?php if ($this->has('logo')): ?>
		    <img src="<?php echo $this->logo ?>" style="float:right;vertical-align:bottom" alt="<?php echo $this->logo_alt ?>" />
		<?php endif; ?>
		<!--a class="button submit"><?php echo $this->_('Submit') ?></a-->
	</p>
</form>
