<?php

/**
 * OntoWiki application module template
 *
 * @version $Id$
 */

//echo "<pre>";
//var_dump($this->menu); die;

$i = 0;

?>

<!-- <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menu<b class="caret"></b></a>
    <ul class="dropdown-menu">-->
        <?php
        foreach ($this->menu as $name => $menu){
            if (is_array($menu)){
                //if( $i++ > 0 ) echo '<li class="divider"></li>';
                //echo '<li class="nav-header">'.$this->_($name).'</li>';
                echo '<li class="dropdown">';
                echo '<a href="#" class="dropdown-toggle" data-toggle="dropdown">'.$this->_($name).'<b class="caret"></b></a>';
                echo '<ul class="dropdown-menu">';
                foreach ($menu as $itemName => $itemContent){
                    if ($itemContent === OntoWiki_Menu::SEPARATOR){
                        echo '<li class="divider"></li>';
                    }elseif ($itemContent instanceof OntoWiki_Menu){
                        echo $this->partial('partials/menu.phtml', array('menu' => array($itemName => $itemContent->toArray(false, false))));
                    }elseif (is_string($itemContent)){
                        echo '<li><a href="'.$itemContent.'">'.$this->_($itemName).'</a></li>';
                    }else{
                        echo '<li>';
                        if (isset($itemContent['url'])){
                            echo '<a href="'.$itemContent['url'].'"';
                        }else{
                            echo '<a';
                        }
                        echo (isset($itemContent['about']) ? 'about="' . $itemContent['about'] . '"' : '');
                        echo (isset($itemContent['class']) ? 'class="' . $itemContent['class'] . '"' : '');
                        echo (isset($itemContent['id']) ? 'id="' . $itemContent['id'] . '"' : '');
                        echo '>';
                        echo $this->_($itemName);
                        echo '</a>';
                        echo '</li>';
                    }
                }
                echo '</ul>';
                echo '</li>';
            }elseif ($menu instanceof OntoWiki_Menu){
                echo $this->partial('partials/menu.phtml', array('menu' => array($name => $menu->toArray(false, false))));
            }elseif ($menu){
                echo '<li><a href="'.$menu.'">'.$this->_($name).'></a></li>';
            }
        } ?>
<!--    </ul>
</li> -->
