<div about="<?php echo $this->skosObject->getUri(); ?>">

<!-- ##### head ##### -->

	<fieldset class="bordered-bottom">
		<div class="medium" rel="http://www.w3.org/1999/02/22-rdf-syntax-ns#type" resource="<?php echo $this->skosObject->getType(); ?>">
			<?php echo substr(strrchr($this->skosObject->getType(), '#'), 1); ?>
		</div>
		<?php if ( $this->skosObject->getPrefLabel() != null ): ?>
			<div class="xx-large" property="<?php echo $this->skosObject->skosPrefLabel; ?>"><?php echo $this->skosObject->getPrefLabel(); ?></div>
		<?php else: ?>
			<div class="messagebox warning">
				<i>skos:prefLabel not available</i>
			</div>
		<?php endif; ?>
		<i class="x-small"><b>URI: </b><?php echo $this->skosObject->getUri(); ?></i>
	</fieldset>
	<?php echo $this->titleHelper->getTitle($this->skosObject->skosAltLabel, $this->locale); ?>:
	<br />
	<?php if ( $this->skosObject->getAltLabel() != null ): ?>
		<span class="indent" property="<?php echo $this->skosObject->skosAltLabel; ?>"><?php echo $this->skosObject->getAltLabel(); ?></span>
	<?php else: ?>
		<i class="indent">not available</i>
	<?php endif; ?>
	<br />
	<?php echo $this->titleHelper->getTitle($this->skosObject->skosNotation, $this->locale); ?>:
	<?php if ( count($this->skosObject->getNotations()) > 0 ): ?>
		<ul class="indent bullets-none separated-horizontal">
			<?php $i = 0; ?>
			<?php foreach ( $this->skosObject->getNotations() as $notation ): ?>
				<?php if ( ++$i == count($this->skosObject->getNotations()) ): ?>
					<li class="last-child" property="<?php echo $this->skosObject->skosNotation; ?>"><?php echo $notation; ?></li>
				<?php else: ?>
					<li property="<?php echo $this->skosObject->skosNotation; ?>"><?php echo $notation; ?></li>
				<?php endif; ?>
			<?php endforeach; ?>
		</ul>
	<?php else: ?>
		<br />
		<i class="indent">not available</i><br />
	<?php endif; ?>
	<br />

	<div class="messagebox info">
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosEditorialNote, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getEditorialNotes()) > 0): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getEditorialNotes() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosEditorialNote; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosEditorialNote; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>		
			<div class="indent">
				<i>no editorial notes available</i>
			</div> 
		<?php endif; ?>
		<br />
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosChangeNote, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getChangeNotes()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getChangeNotes() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosChangeNote; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosChangeNote; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no change notes available</i>
			</div> 
		<?php endif; ?>
	</div>
	<br />

<!-- ##### information ##### -->

	<b class="indent">Information</b>
	<hr class="seperator" />
	<div class="indent">
		<br />
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosDefinition, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getDefinitions()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getDefinitions() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosDefinition; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosDefinition; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no definitions available</i>
			</div> 
		<?php endif; ?>
		<br />
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosNote, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getNotes()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getNotes() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosNote; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosNote; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no notes available</i>
			</div>
		<?php endif; ?>
		<br />
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosScopeNote, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getScopeNotes()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getScopeNotes() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosScopeNote; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosScopeNote; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no scope notes available</i>
			</div>
		<?php endif; ?>
	</div>
	<br />

<!-- ##### other ##### -->

	<b class="indent">Other</b>
	<hr class="seperator" />
	<div class="indent">
		<br />
		<h4>
			<?php echo $this->titleHelper->getTitle($this->skosObject->skosHistoryNote, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getHistoryNotes()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getHistoryNotes() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosHistoryNote; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosHistoryNote; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no history notes available</i>
			</div>		
		<?php endif; ?>
		<br />
		<h4>
				<?php echo $this->titleHelper->getTitle($this->skosObject->skosExample, $this->locale); ?>
		</h4>
		<hr class="seperator" />
		<?php if ( count($this->skosObject->getExamples()) > 0 ): ?>
			<div class="indent">
				<ul class="backgrounded spaced-vertical">
					<?php $i = 0; ?>
					<?php foreach ($this->skosObject->getExamples() as $note): ?>
						<?php if ( (++$i % 2) == 0 ): ?>
							<li property="<?php echo $this->skosObject->skosExample; ?>"><?php echo $note; ?></li>
						<?php else: ?>
							<li class="odd" property="<?php echo $this->skosObject->skosExample; ?>"><?php echo $note; ?></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php else: ?>
			<div class="indent">
				<i>no examples available</i>
			</div>	
		<?php endif; ?>
	</div>

</div>
