<div id="newsfeed">
    <?php $entrycount = 0; foreach ($this->entries as $entry) : ?>
    <div class="hentry <?php if ($entrycount == 0) echo 'first' ?>">
        <h4><a title="permalink"
           class="hasMenu Resource"
           about="<?php echo $entry['link'] ?>"
           href="<?php echo $entry['link'] ?>"><?php echo $entry['title'] ?></a></h4>
        <p class="meta hideme">
            <?php if (isset($entry['dateModified'])) :?>
                <?php echo $entry['dateModified'] ?>
            <?php endif; ?>
            <?php if (isset($entry['authors'][0])) :?>
                <?php if (is_array($entry['authors'][0]) && isset($entry['authors'][0]['name'])): ?>
                    | <?php echo $entry['authors'][0]['name'] ?>
                <?php else: ?>
                    | <?php echo $entry['authors'][0] ?>
                <?php endif; ?>
            <?php endif; ?>
        </p>
        <?php if ( (isset($entry['description'])) && ($entry['description'] != $entry['title']) ):?>
            <p>
                <?php echo str_replace('[...]', '', substr(strip_tags($entry['description']), 0, 200)) ?> ...
                <a href="<?php echo $entry['link'] ?>">read<span class="hideme"> &quot;<?php echo $entry['title'] ?>&quot;</span></a>
            </p>
        <?php endif; ?>
    </div>
    <?php endforeach; ?>
</div>