<?php
/**
 * This file is part of the {@link http://ontowiki.net OntoWiki} project.
 *
 * @copyright Copyright (c) 2011, {@link http://aksw.org AKSW}
 * @license http://opensource.org/licenses/gpl-license.php GNU General Public License (GPL)
 */

/**
 * default template if no other template can be applied
 */

?>
<h1><?php echo $this->title ?></h1>

<?php
echo $this->literal(array('tag' => 'div', 'class' => 'content')); // uses default content properties
