<?php
/**
 * OntoWiki filter module template
 *
 * @version $Id: filter.phtml 4296 2009-10-13 12:16:54Z norman.heino $
 */
$odd = false;
?>
<div id="filterbox">
    <!--ul id="list"></ul-->
    <form name="search" method="get" action="<?php echo $this->actionUrl ?>">
	<p class="width98">
		<label class="display-block" for="filtersearchtext-input"><?php echo $this->_('Search in list') ?></label>
		<input class="text width99 inner-label" type="text" id="filtersearchtext-input" name="s" value="<?php echo $this->s ?>" />
	</p>
	
	<p>
		<!--a class="button submit"><?php echo $this->_('Submit') ?></a-->
	</p>
    </form>
    <p>
        <a class="minibutton" href="javascript:showAddFilterBox()" />Add complex Filter</a>
        <a class="minibutton" href="javascript:removeAllFilters()" />Clear</a>
    </p>
    <br />
    <?php if ($this->filter) : ?>
    <?php $linkurl = new OntoWiki_Url(array('route' => 'properties'), array('r')) ?>
    <ul class="separated-vertical">
        <?php foreach ($this->filter as $filter) : 
                if(isset($filter['hidden']) && $filter['hidden']){continue;} ?>
        <li id="<?php echo $filter['id'] ?>"
            class="<?php echo $odd ? 'odd' : 'even'; $odd = !$odd; ?> filter"
            >
            <?php if($filter['mode'] == "filterbox"): ?>
            <a  class="hasMenu"
                about="<?php echo $filter['property'] ?>"
                href="<?php echo (string) $linkurl->setParam('r', $filter['property'], true) ?>">
                <?php echo $this->titleHelper->getTitle($filter['property']) ?>
            </a>
            <?php if ($filter['isInverse'] == true) : ?>
                <sup>-1</sup>
            <?php endif ?>
            <?php echo $filter['filter'] ?>
            <?php if ($filter['value1']) : ?>
                <?php if ($filter['valuetype'] == 'uri') : ?>
                    <a  class="hasMenu"
                        about="<?php echo $filter['value1']; ?>"
                        href="<?php echo (string) $linkurl->setParam('r', $filter['value1'], true) ?>">
                        <?php echo $this->titleHelper->getTitle($filter['value1']); ?>
                    </a>
                <?php else : ?>
                    <strong>"<?php echo $filter['value1'] ?>"</strong>
                <?php endif ?>
            <?php endif ?>
            <?php endif; if($filter['mode'] == "typeFilter") : ?>
                    Type: <a  class="hasMenu"
                        about="<?php echo $filter['type']; ?>"
                        href="<?php echo (string) $linkurl->setParam('r', $filter['type'], true) ?>">
                        <?php echo $this->titleHelper->getTitle($filter['type']); ?>
                    </a>
            <?php endif; if($filter['mode'] == "searchFilter") : ?>
                    Search: <?php echo $filter['searchText']; ?>
            <?php endif; if($filter['mode'] == "given") : ?>
                    Base Query
            <?php endif; ?>
                    &nbsp;&nbsp;&nbsp;<a class="delete">x</a>
        </li>
        <?php endforeach ?>
    </ul>
    <?php endif ?>

   
    <div id="addFilterWindowOverlay">
        <div class="window" id="addwindow">
            <h2 class="title">Add Filter</h2>
            <table>
                <tr>
                    <td>
                        <select id="property" size="7">
                            <?php foreach($this->properties as $key => $property){ ?>
                            <option about="<?php echo $property['uri']; ?>" class="Resource"><?php echo $property["title"]; ?></option>
                            <?php } ?>
                            <?php foreach($this->inverseProperties as $key => $property){ ?>
                            }
                            <option about="<?php echo $property['uri']; ?>" class="Resource InverseProperty"><?php echo $property["title"]; ?> (inverse)</option>
                            <?php } ?>
                        </select>
                    </td>
                    <td style="vertical-align:middle">
                        equals
                    </td>
                    <td>
                        <select id="possiblevalues" size="7">
                                <option>none loaded</option>
                        </select>
                    </td>
                </tr>
            </table>
            <div style="padding:10px;">
                or<br/>
                <select id="resttype">
                        <option>contains</option>
                </select>
                <input type="text" id="value"/>
                <formset><a id="add" class="button minibutton">set</a>
                <a id="addwindowhide" class="button minibutton">cancel</a></formset>
            </div>
        </div>
    </div>
</div>
