<?php

/**
 * OntoWiki user details template
 *
 * @author Norman Heino <norman.heino@gmail.com>
 * @author Philipp Frischmuth <pfrischmuth@googlemail.com>
 * @version $Id: userdetails.phtml 2917 2009-04-21 12:13:33Z norman.heino $
 */

?>

<?php if (!isset($this->errorFlag)): ?>    
<fieldset>

    <div>
        <input type="hidden" name="checkwebid" />
        <label for="webid-input"><?php echo $this->_('WebID') ?></label>
        <input class="text" id="webid-input" type="text" name="webid-input" />
        <span style="font-size: .8em"><?php echo $this->_('If not provided a WebID will be generated.') ?></span>
        <br class="clearall">
    </div>
    <div class="clearall"></div>
</fieldset>
<?php endif; ?>
