<fieldset id="upload" class="form">
    <legend></legend>
    <div>
        <label for="file_uri"><?php echo $this->_('Resource URI of the Plugin-Sourcecode:')?></label>
		<input class="text prefix-value" value="<?php echo $this->defaultUri ?>" type="text" name="file_uri" id="file_uri" size="10" />
    </div>
    <div>
        <label for="file-input">
            <?php echo sprintf($this->_('Or upload to the repository (max. %1$sB):'), preg_replace('/([kMG])/', ' $1', ini_get('upload_max_filesize'))) ?>
        </label>
        <input type="file" id="file-input-source" name="plugin_source" />
        <br class="clearall" />
    </div>
    <legend></legend>
    <div>
        <label for="file_uri"><?php echo $this->_('Resource URI of the Plugin-Logo-Sourcecode:')?></label>
		<input class="text prefix-value" value="<?php echo $this->defaultUri ?>" type="text" name="logo_uri" id="logo_uri" size="10" />
    </div>
    <div>
        <label for="file-input">
            <?php echo sprintf($this->_('Or upload to the repository (max. %1$sB):'), preg_replace('/([kMG])/', ' $1', ini_get('upload_max_filesize'))) ?>
        </label>
        <input type="file" id="file-input-log" name="logo_source" />
        <br class="clearall" />
    </div>
</fieldset>