<?php
if(class_exists("QuerybuildingHelper")){
$this->placeholder('main.window.innerwindows')->append(
        $this->partial('partials/window.phtml', array(
                'headinglevel' => 2,
                'title'        => $this->_('Save Query'),
                'content'      => $this->partial('partials/savepartial.phtml'),
                'cssClasses'   => 'graphicalquerybuilder',
                'cssId'        => 'savebox'
        ))
);
}
$this->placeholder('main.window.innerwindows')->append(
        $this->partial('partials/window.phtml', array(
                'headinglevel' => 2,
                'title'        => $this->_('Properties'),
                'content'      => $this->partial('graphicalquerybuilder/gqbsidepanel.phtml'),
                'cssClasses'   => '',
                'cssId'        => 'gqb-side-panel'
        ))
);
?>
<div class="messagebox info" id="gqbinfo" style="text-align: left;">&nbsp;</div>
<div id="gqbcenter">
    <div id="gqbbuttoncontrolpanel" class="messagebox">
            <div class="toolbar">
                    <a id="gqbdisplayresultsbutton" class="button submit">Ergebnis anzeigen</button>
                    <a id="gqbshowquerybutton" class="button"><img src="<?php echo $this->componentUrlBase; ?>extensions/themes/silverblue/images/icon-hidden-mini.png"/>Query anzeigen</button>
                    <a class="button gqbsetlangbutton" lang="en">en</a>
                    <a class="button gqbsetlangbutton" lang="de">de</a>
            </div>
    </div>
    <div id="gqbcanvas"></div>
    <div class="gqbFunButton" style="background-color: #fefefe; cursor: default; height: 5px; width: 5px;" ></div>
</div>
<div id="gqbDialogBg"></div>
<div id="gqbDialogUnionInt">
        <div id="gqbDialogUnionIntLabel">Wie sollen die Klassen verknüpft werden?  Durch:</div>
        <button id="gqbDialogUnionIntUnion" style="position:relative; width:80px; height:30px;">Vereinigung</button>
        <button id="gqbDialogUnionIntInt" style="position:relative; width:83px; height:30px;">Durchschnitt</button>
        <button id="gqbDialogUnionIntCancel" style="position:relative; width:73px; height:30px;">Abbrechen</button>
</div>
<div id="gqbDialogLinkSel">
        <div id="gqbDialogLinkSelLabel">Klassen über welche Verbindung verbinden?</div>
        <select id="gqbDialogLinkSelSel" style="position:relative; height:23px;"></select>
        <button id="gqbDialogLinkSelOk" style="position:relative; width:40px; height:30px;">OK</button>
        <button id="gqbDialogLinkSelCancel" style="position:relative; width:73px; height:30px;">Abbrechen</button>
</div>
