<div id="gqbObjProperties">
					<h3 id="gqbObjPropertiesType"></h3>
					<div id="gqbPatternProperties">
						<strong id="gqbPatternPropertiesInstLabel">Instanzen: 0</strong><br />
						<input id="gqbPatternPropertiesDistinct" type="checkbox" /> DISTINCT<br />
						<hr class="gqbhorizontalruler" />
						<strong id="gqbPatternPropertiesSelectedClassLabel">SelectedClass:</strong><br />
						<div id="gqbPatternPropertiesSelectedClass"></div>
					</div>
	
					<div id="gqbClassProperties">
						<strong id="gqbClassPropertiesRdftypeLabel">Typ:</strong> <span id="gqbClassPropertiesRdftype"></span><br />
						<strong id="gqbClassPropertiesNumInstancesLabel">Anzahl Instanzen:</strong> <span id="gqbClassPropertiesNumInstances"></span><br />
						<button id="gqbShowPatternButton" class="button gqbbutton">Pattern anzeigen</button><br />
						<strong id="gqbClassPropertiesWithChildsLabel">Mit Unterklassen:</strong> <input type="checkbox" id="gqbClassPropertiesWithChilds"/><br />
					
						<hr class="gqbhorizontalruler" style="margin-top:15px;" />
						<div id="gqbPropertySwitcher">
							<div style="float:right;">
								<img src="../../../extensions/components/graphicalquerybuilder/resources/images/minus.gif" id="gqbMinimizeProperties" alt="" />
								<img src="../../../extensions/components/graphicalquerybuilder/resources/images/plus.gif" id="gqbMaximizeProperties" alt="" style="display: none;" />
							</div>
							<strong id="gqbClassPropertiesPropertiesLabel">Eigenschaften:</strong>
						</div>
						<ul id="gqbClassPropertiesProperties" style="list-style-type: none;">
						</ul>
						<hr class="gqbhorizontalruler" />
						<strong id="gqbClassPropertiesRestrictionsLabel">Einschränkungen:</strong><br />
						<div id="gqbClassPropertiesAddRestriction"></div>
						<ul id="gqbClassPropertiesRestrictions" class="filetree treeview-famfamfam treeview">
						<li id="gqbclassrestrictionsexist">
						<span id="gqbaddrestrictionbuttonand" class="gqb-button gqb-button-add" title="UND-Einschränkung hinzufügen"></span>
						<span class="folder">&and;</span>
						<div id="addrestrictionandpanel"></div>
						<ul id="gqbclassrestrictionstoplevelmembers">
						<li class="gqbclassrestrictionstoplevelmember"><span class="folder">&or;</span>
						<ul class="gqbclassrestrictionssecondlevelmembers">
						<li><span class="file gqbclassrestrictionssecondlevelmember">restr1</span></li>
						</ul>
						</li>
						</ul>
						</li>
						<li id="gqbclassrestrictionsnotexist">
						<span id="gqbaddrestriction" class="gqb-button gqb-button-add" title="Einschränkung hinzufügen"></span><div id="gqbaddrestrictionlabel">keine</div></li>
						</ul>
						<hr class="gqbhorizontalruler" />
						<strong id="gqbClassPropertiesOutgoinglinksLabel">verfügbare Beziehungen:</strong><br/>
						<ul id="gqbClassPropertiesOutgoinglinks">
						</ul>
						<strong id="gqbClassPropertiesSelectedlinksLabel">ausgewählte Beziehungen:</strong><br/>
						<ul id="gqbClassPropertiesSelectedlinks">
						</ul>
					</div>
