<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUri ?>" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/main.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/reset.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/text.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/grid.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/layout.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/nav.css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/ie.css" media="screen" /><![endif]-->

    <!-- jQuery -->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>

    <!--script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-fluid16.js"></script-->

    <title><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?> :: LOD2</title>
</head>
<body about="<?php echo $this->resourceUri?>">
<?php
    // this is the standard template data
    $templateData = array(
                    'title' => $this->descriptionHelper->getTitle($this->resourceUri),
                    'resourceUri' => $this->resourceUri,
                    'description' => $this->description[$this->resourceUri],
                    'descriptionHelper' => $this->descriptionHelper,
                    'options'           => $this->options
            );
    function printNavi($navi, $titleHelper, $depth){
        if(is_array($navi) && count($navi)>0):?>
                    <?php foreach ($navi as $navurl => $subnavi) : ?>
                    <li>
                        <a href="<?php echo $navurl ?>"><?php for($i=0; $i< $depth; $i++){echo "&nbsp;&nbsp;";} echo $titleHelper->getTitle($navurl) ?></a>
                        <?php printNavi($subnavi, $titleHelper, $depth+1); ?>
                    </li>
                    <?php endforeach; ?>
       <?php endif; 
   }

?>
<div class="container_16">
    <div class="grid_16">
        <h1 id="branding">
            <a href="<?php echo $this->site['index'] ?>"><?php echo $this->site['name'] ?></a>
        </h1>
    </div>
    <div class="clear"></div>
    <div class="grid_16">
        <ul class="nav main">
            <?php foreach ($this->navigation as $navurl => $subnavi) : ?>
            <li>
                <a href="<?php echo $navurl ?>"><?php echo $this->descriptionHelper->getTitle($navurl) ?></a>
                <ul><?php printNavi($subnavi, $this->descriptionHelper, 0); ?> </ul>
            </li>
            <?php endforeach; ?>

            <li class="secondary">
                <a href="<?php echo $this->wikiBaseUri ?>/index">OntoWiki</a>
                <ul>
                    <li><a href="<?php echo $this->wikiBaseUri ?>view?r=<?php echo $this->resourceUri ?>">View/Edit</a></li>
                    <li><a href="<?php echo $this->wikiBaseUri ?>source/edit?r=<?php echo $this->resourceUri ?>">Source</a></li>
                </ul>
            </li>
        </ul>

    </div>
    <div class="clear"></div>
    <div class="grid_16">
        <h2 id="page-heading"></h2>
    </div>


    <div class="grid_11">
        <?php echo $this->partial('lod2/main.phtml', $templateData) ?>
        <?php echo $this->partial('lod2/query.phtml', $templateData) ?>
        <?php echo $this->partial('lod2/feed.phtml', $templateData) ?>
    <div class="clear"></div>

        <div class="box">
            <h2 id="">TODOs :-(</h2>
        <ul>
            <li>Norm: Kann man den modulen den options-array durchreichen? (z.B. um resource uris als links zu nehmen)
            <ul>
                <li>Ja, aber bisher nur Render-Optionen wie CSS-Klasse und -ID. Könnte was an die getContents() durchreichen, aber das Modul müsste dann natürlich auf die exakten Keys reagieren.</li>
                <li>ja, das wäre notwendig</li>
            </ul>
            </li>
            <li>Norm: linked data scheint nicht mehr zu gehen</li>
        </ul>

        <ul>Später:
            <li>Wie werden Dokumente (z.B. PDFs) benutzt (über files component)</li>
        </ul>

        </div>

        <div class="box " style="padding:0;">
            <h2 style="margin:0">
                <a href="#" id="toggle-grid">DONE :-)</a>
            </h2>
        </div>
        <div id="grid" class="box">
            <ul>
                <li>Welche view-variablen sind notwendig (mal bei Wordpress schauen)</li>
                <li>Seebi: Mehr LOD2 Daten ...</li>
                <li>Wie wird der URI helper zur Verfügung gestellt... new OntoWiki_Url</li>
                <li><del>Norm</del> Seebi: SPARQL API Methode + Listen methode?</li>
                <li>Jonas: View_Helper navigation(string $uriOfSKOSContainer) bitte komplette Navi ausgeben (nach sysont:order sortieren); ausserdem: /Stack scheint manchmal "Stack" und manchmal "Technology Stack" zu heißen ...</li>
                <li>Jonas: View_Helper lastchange($resourceUri)</li>
                <li>Wie werden die Templates pro Klasse benutzt
                    <ul>
                        <li>Idee: templateHelper bekommt beliebige URI und lädt ein passendes Template. Das kann im einfachsten Fall ein hartgecodetes Mapping der <code>rdf:type</code>s sein.</li>
                        <li>Ne andere möglichkeit hab ich gerade gepusht ... siehe main.phtml</li>

                    </ul>
                </li>
                <li>Wie wird denn die index-page config umgesetzt? (also link von / auf /index....)
                    <ul>
                        <li>Es gibt eine Route namens "empty", die auf den leeren String (nach der Base-URI) reagiert und einen Default-Controller und eine Default-Action hat.</li>
                        <li>Wir wollen ja aber zu einer URI redirecten, also z.B. von / auf /Welcome</li>
                        <li>solution: index parameter in site-specific config.ini</li>
                    </ul>
                </li>
                <li>Norm: ViewHelper Directory für components</li>
                <li>Norm: Linked Data URIs auf den site controller forwarden?</li>
                    SiteHelper reagiert auf Event <code>onShouldLinkedDataRedirect</code>, setzt neuen
                     Controller/Action und gibt <code>false</code> (= should not redirect) zurück.
                <li>Wie wird die Startseite erreichbar (also eigentlich das OW basedir)
                    <pre>
            index.default.controller = "site"
            index.default.action = "lod2"
                    </pre>
                    SiteHelper reagiert auf Event <code>onPostBootstrap</code> und injiziert SiteController und aktuell aktive
                    Site als Standard-Route in den Router.
                </li>
                <li>Seebi: Test Modell</li>
                <li>Jonas: site config für Site-Modell
                    Test Site config:
                    <ul>
                    <?php foreach ($this->site as $key => $value): ?>
                        <li><?php echo sprintf('%s = %s', $key, $value) ?></li>
                    <?php endforeach; ?>
                    </ul>
                </li>
                <li>Seebi: site config key model=xxx wird jetzt default-selected</li>
                <li>Norm: CBD + titles der selected resource über ressource klasse</li>
                CBD for current resource:
                <?php var_dump($this->description) ?>
                <p>
                    <strong>TODO: lieber doch symmetrisch?</strong>
                    <blockquote cite="http://www.w3.org/DesignIssues/LinkedData.html">The subgraph returned has been referred to as "minimum Spanning Graph (MSG [@@ref] ) or  RDF molecule [@@ref], depending on whether nodes are considered identified if they can be expressed as a path of function, or reverse inverse functional properties. A concise bounded description, which only follows links from subject to object,  does not work.</blockquote>
                    aus: <a href="http://www.w3.org/DesignIssues/LinkedData.html">Linked Data design issues</a>
                </p>
                <li>Norm: titles über TitleHelper aller in der CBD enthaltenen ressource?</li>
                <pre><code><?php echo $this->escape('<?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?>')?></code></pre>
                Beispiel (Code s.&thinsp;o.): <?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?>
                <li>Norm: Wie wird modul-content gerendert (eigener context)</li>
                    <pre>
            echo $this->module('ttt', array('noChrome' => true)); // ein bestimtes Modul oder
            echo $this->modules('sites.lod2', array('noChrome' => true)); // alle Module für Context 'sites.lod2'
                    </pre>
                    Beispiel: <?php echo $this->modules('sites.lod2', array('noChrome' => true, 'foo' => 'ttt')) ?>
                    TODO: Was ist mit Titel, Menüs, Modulen mit Tabbed Content?
                <li>Jonas: Wie werden Bilder aus dem CSS referenziert</li>
                    <pre>
            bitte testen
                    </pre>
            </ul>
        </div>

    </div>


    <div class="grid_5">
        <div class="box">
            <h2>Minimap</h2>
            <?php echo $this->module('minimap', array('noChrome' => true)); ?>
        </div>
        <div class="box">
            <h2>Linking Resources</h2>
            <?php echo $this->module('linkinghere', array('noChrome' => true)); ?>
        </div>
        <div class="box">
            <h2>Nearby</h2>
            <?php echo $this->module('similarinstances', array('noChrome' => true)); ?>
        </div>
        <div class="box">
            <h2>Last Changes</h2>
            <?php echo $this->module('lastchanges', array('noChrome' => true)); ?>
        </div>
    </div>


    <div class="grid_16" id="site_info">
        <div class="box">
            <p>This page is proudly powered by
                <a href="http://ontowiki.net" title="OntoWiki is a Semantic Data Wiki enabling the collaborative creation and (linked data) publication of RDF knowledge bases."><?php echo $this->generator ?></a>,
                <a href="http://www.designinfluences.com/fluid960gs/" title="The 960 Grid System is an effort to streamline web development workflow by providing commonly used dimensions, based on a width of 960 pixels.">Fluid 960 Grid System</a> and
                <a href="jquery.com" title="jQuery is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development.">jQuery</a>.

        </div>
    </div>
    <div class="clear"></div>
</div>

</body>
</html>