<?php

/**
 * OntoWiki create model template
 */

?>
<input type="hidden" name="referer" value="<?php echo $this->referer ?>">
<fieldset>
<legend><?php echo $this->_('Basic Model Information'); ?></legend>
    <div>
        <label><?php echo $this->_('Title') ?></label>
        <input type="text" class="text" />
    </div>
    <div>
        <label><?php echo $this->_('URI') ?></label>
        <input type="text" class="text" />
        <br class="clearall" />
    </div>
</fieldset>

<fieldset>
<legend><?php echo $this->_('Data Creation Options'); ?></legend>
    <div>
        <?php // if model URI is set, don't allow empty model creation ?>
        <label class="checkboxradio" for="r01">
            <input type="radio" class="radio" name="activeForm" id="r01" value="empty" />
            <?php echo $this->_('Create an Empty Knowledge Base') ?>
        </label>
        <br class="clearall" />

        <?php if (ini_get('allow_url_fopen')): ?>
            <label class="checkboxradio" for="r02">
                <input type="radio" class="radio" name="activeForm" id="r02" value="import" />
                <?php echo $this->_('Import From the Web') ?>
            </label>
            <br class="clearall" />
        <?php endif; ?>

        <label class="checkboxradio" for="r03">
            <input type="radio" class="radio" name="activeForm" id="r03" value="upload" />
            <?php echo $this->_('Upload a File') ?>
        </label>
        <br class="clearall" />

        <label class="checkboxradio" for="r04">
            <input type="radio" class="radio" name="activeForm" id="r04" value="paste" />
            <?php echo $this->_('Paste Source') ?>
        </label>
        <br class="clearall" />
    </div>
</fieldset>

