<?php

/**
 * OntoWiki create model template
 */

?>
<fieldset>
<legend><?php echo $this->_('Basic information'); ?></legend>
    <div>
        <label><?php echo $this->_('Title') .' '. $this->_('(leave blank if your import provides the name)') ?></label>
        <input type="text" class="text" />
    </div>
    <div>
        <label><?php echo $this->_('URI (leave blank for auto creation)') ?></label>
        <input type="text" class="text" name="modeluri" />
        <br class="clearall" />
    </div>
</fieldset>

<!-- fieldset>
    <legend><?php echo $this->_('Access Control and Visibility'); ?></legend>
    <div>
        <label class="checkboxradio" for="aclpublic">
            <input type="radio" class="radio" name="acl" id="aclpublic" value="public" checked />
            <?php echo $this->_('public (readable for everyone / writeable for admins)') ?>
        </label>
        <label class="checkboxradio" for="aclopen">
            <input type="radio" class="radio" name="acl" id="aclopen" value="open" />
            <?php echo $this->_('open (readable and writeable for everyone)') ?>
        </label>
        <label class="checkboxradio" for="aclclosed">
            <input type="radio" class="radio" name="acl" id="aclclosed" value="closed" />
            <?php echo $this->_('closed (readable and writeable for admins)') ?>
        </label>
    </div>
</fieldset-->

<?php if (count($this->importActions) > 0) : ?>
<fieldset>
    <legend><?php echo $this->_('Data import actions'); ?></legend>
    <div>
<?php foreach ($this->importActions as $key => $action) : ?>
        <label class="checkboxradio" for="import-<?php echo $key ?>">
            <input
                type="radio" class="radio" name="importAction"
                id="import-<?php echo $key ?>" value="<?php echo $key ?>"
                <?php echo (isset($action['parameter']) ? $action['parameter'] : '' ) ?>
            />
            <?php echo $this->_($action['label']) ?>
        </label>
        <br class="clearall" />
<?php endforeach; ?>
    </div>
</fieldset>
<?php endif; ?>

