<?php $confStr = json_encode(array('enabled'=>true, 'private'=>$this->config));?>
hier ein minimal working example - direkt in json rumschreiben...<br/>
alternativ kann man eine schöne gui machen die am ende den json string in die passenden post parameter packt.<br/>
nur der enabled wert und und die private config kann geändert werden. <br/>
mann muss eingeloggt sein damit es funktioniert. es wird ajax empfohlen weil man sonst auf der standard config seite landet.
<form action="<?php echo $this->urlBase;?>exconf/conf" method="POST">
    <input type="hidden" name="name" value="community" />
    <textarea name="config"><?php echo $confStr; ?></textarea> <br/>
    <input type="submit" name="send" value="senden"/>
</form>