<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper,
);
?>

<?php if ($content = trim($this->partial('lod2/content.phtml', $templateData))): ?>

<div class="maincontent">
    <div class="section">
        <h3><?php echo $this->title ?></h3>
            <?php if (isset($this->description['http://lod2.eu/schema/partner'][0]['value'])) {
                $partnerResourceUri = $this->description['http://lod2.eu/schema/partner'][0]['value'];
                $partnerResource = new OntoWiki_Resource($partnerResourceUri, OntoWiki::getInstance()->selectedModel);
                // echo $partnerResource->getTitle();
                // TODO: Partner Liste in inline table
            }
            ?>
        <div class="section-content">
            <?php echo $content; ?>
            
            <?php if (isset($this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'])): ?><div>Homepage: <a href="<?php 
                echo $this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'] ?>"><?php 
                echo $this->description['http://usefulinc.com/ns/doap#homepage'][0]['value'] 
            ?></a></div><?php endif; ?>
            
            <?php if (isset($this->description['http://lod2.eu/schema/partner'])): ?><div>Partner: <?php 
                echo $this->objectlist($this->description['http://lod2.eu/schema/partner'], $this->descriptionHelper); 
            ?></div><?php endif; ?>
        </div>
    </div>
</div>

<?php endif; ?>


