sed s/lod2:deliveryDate\ \"M1\"./lod2:deliveryDate\ \"2010-09-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M2\"./lod2:deliveryDate\ \"2010-10-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M3\"./lod2:deliveryDate\ \"2010-11-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M4\"./lod2:deliveryDate\ \"2010-12-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M5\"./lod2:deliveryDate\ \"2011-01-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M6\"./lod2:deliveryDate\ \"2011-02-28\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M7\"./lod2:deliveryDate\ \"2011-03-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M8\"./lod2:deliveryDate\ \"2011-04-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M9\"./lod2:deliveryDate\ \"2011-05-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M10\"./lod2:deliveryDate\ \"2011-06-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M11\"./lod2:deliveryDate\ \"2011-07-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M12\"./lod2:deliveryDate\ \"2011-08-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M13\"./lod2:deliveryDate\ \"2011-09-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M14\"./lod2:deliveryDate\ \"2011-10-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M15\"./lod2:deliveryDate\ \"2011-11-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M16\"./lod2:deliveryDate\ \"2011-12-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M17\"./lod2:deliveryDate\ \"2012-01-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M18\"./lod2:deliveryDate\ \"2012-02-29\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M19\"./lod2:deliveryDate\ \"2012-03-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M20\"./lod2:deliveryDate\ \"2012-04-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M21\"./lod2:deliveryDate\ \"2012-05-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M22\"./lod2:deliveryDate\ \"2012-06-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M23\"./lod2:deliveryDate\ \"2012-07-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M24\"./lod2:deliveryDate\ \"2012-08-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M25\"./lod2:deliveryDate\ \"2012-09-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M26\"./lod2:deliveryDate\ \"2012-10-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M27\"./lod2:deliveryDate\ \"2012-11-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M28\"./lod2:deliveryDate\ \"2012-12-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M29\"./lod2:deliveryDate\ \"2013-01-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M30\"./lod2:deliveryDate\ \"2013-02-28\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M31\"./lod2:deliveryDate\ \"2013-03-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M32\"./lod2:deliveryDate\ \"2013-04-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M33\"./lod2:deliveryDate\ \"2013-05-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M34\"./lod2:deliveryDate\ \"2013-06-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M35\"./lod2:deliveryDate\ \"2013-07-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M36\"./lod2:deliveryDate\ \"2013-08-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M37\"./lod2:deliveryDate\ \"2013-09-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M38\"./lod2:deliveryDate\ \"2013-10-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M39\"./lod2:deliveryDate\ \"2013-11-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M40\"./lod2:deliveryDate\ \"2013-12-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M41\"./lod2:deliveryDate\ \"2014-01-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M42\"./lod2:deliveryDate\ \"2014-02-28\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M43\"./lod2:deliveryDate\ \"2014-03-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M44\"./lod2:deliveryDate\ \"2014-04-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M45\"./lod2:deliveryDate\ \"2014-05-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M46\"./lod2:deliveryDate\ \"2014-06-30\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M47\"./lod2:deliveryDate\ \"2014-07-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3
sed s/lod2:deliveryDate\ \"M48\"./lod2:deliveryDate\ \"2014-08-31\^\^xsd:date\"./ deliverables.n3 >deliverables.tmp; mv deliverables.tmp deliverables.n3

