<?php
// this is the standard template data
$templateData = array(
    'title' => $this->title,
    'resourceUri' => $this->resourceUri,
    'description' => $this->description,
    'descriptionHelper' => $this->descriptionHelper,
);

if (isset($this->description['http://lod2.eu/schema/contentSideTop'])) {
    foreach ($this->description['http://lod2.eu/schema/contentSideTop'] as $property) {
        if (isset($property['value'])) {
            echo $property['value'];
        }
    }
}
