<?php
    $moduleOptions = array('noChrome' => true);
    
    if ($this->resourceUri == 'http://lod2.eu/Welcome') {
        // fech feed module with relevant feeds
        $moduleOptions['relevant'] = 'http://lod2.eu/schema/feedRelevantFor';
    }
    
    $content = trim($this->module('feeds', $moduleOptions));
?>

<?php if (!empty($content)): ?>
<div class="section">
    <h3>News</h3>
    <div class="section-content">
        <?php echo $content; ?>
    </div>
</div>
<?php endif; ?>
