<?php
$entry = $this->element;

if($entry["generator"][0]["value"]=="qb") {
    $base = $this->urlBase."querybuilder/manage";
    $base .= "?patterns=".htmlentities($entry["json"][0]["value"]);
    $base .= "&label = ".$entry["description"][0]["value"];
} elseif ($entry["generator"][0]["value"]=="gqb") {
    $base = $this->urlBase."graphicalquerybuilder/display?open=true";
    $base .= "&queryuri=".htmlentities($entry["query"][0]["value"]);
}
$qelink = Erfurt_App::getInstance()->getConfig()->urlBase."queries/editor?immediate=1&query=".urlencode($entry['query'][0]["value"]);
?>
<a style="margin:2px;" class="minibutton" href="<?php echo $qelink; ?>">qe</a>
<?php if($entry["generator"][0]["value"]=="qb" || $entry["generator"][0]["value"]=="gqb") {?>
&nbsp;<a style="margin:2px;" class="minibutton" href="<?php echo $base;?>">
        <?php echo $entry["generator"][0]["value"]; ?>
</a><?php
}
?>