<?php
/**
 * OntoWiki LOV prefix template
 */
?>
<p class="messagebox info">The <a href="http://prefix.cc">prefix.cc service</a> allows for prefix searches.</p>
<p>
    <label
        class="display-block onlyAural"
        for="prefixcc-search-input">Please type a known prefix.cc prefix</label>
    <input
        id="prefixcc-search-input"
        class="text width99 inner-label"
        type="text"
        value=""
        name="prefixcc-search-input"/>
</p>
<p class="messagebox error">Not implemented yet</p>
