<?php
/*
 * This template does not output anything but a specific partial output
 */

// do nothing, if we do not have a standard resource query from ontowiki ...
if (!isset($this->resourceUri)) {
    return;
}

$resource = new OntoWiki_Resource($this->resourceUri, OntoWiki::getInstance()->selectedModel);
$fullDescription = $resource->getDescription();
$description = $fullDescription[$this->resourceUri];
$descriptionHelper = $resource->getDescriptionHelper();

$title = $descriptionHelper->getTitle($this->resourceUri);
$resourceUri = $this->resourceUri;

$url = new OntoWiki_Url(array('route' => 'properties'), array('r'));
$url->setParam('r', $this->resourceUri, true);
?>
<li><a href="<?php echo $url ?>"><?php echo $title ?></a></li>
