<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
<head>
    <title>OntoWiki</title>

    <?php if ($this->has('jsonVars')): ?>
        <script type="text/javascript">
            <?php echo $this->jsonVars ?>
        </script>
    <?php endif; ?>

    <!-- stylesheets -->
    <style type="text/css" media="screen">@import "extensions/themes/mobile/jqtouch/jqtouch.min.css";</style>
    <style type="text/css" media="screen">@import "extensions/themes/mobile/apple/theme.min.css";</style>

    <!-- jQTouch -->
    <script type="text/javascript" src="extensions/themes/mobile/jqtouch/jquery.1.3.2.min.js" charset="utf-8"></script>
    <script type="application/x-javascript" src="extensions/themes/mobile/jqtouch/jqtouch.js" charset="utf-8"></script>

    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.livequery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.json.js"></script>

    <script type="text/javascript" charset="utf-8" src="extensions/themes/mobile/base.js"></script>

    <?php echo $this->headScript() ?>
</head>
<body>
    <div id="home">
        <div class="toolbar">
            <!-- <a href="#innercontent" class="button leftButton flip">Login</a> -->
            <h1>OntoWiki Mobile</h1>
        </div>
        <?php echo $this->modules('main.mobile.baselist') ?>
    </div>
    <div id="nav">
        <div class="toolbar">
            <a href="#" class="back">Back</a>
            <h1 id="nav-title">title</h1>
        </div>
        <?php echo $this->modules('main.mobile.navigation') ?>
    </div>
    <div id="list">
        <div class="toolbar">
            <a href="#nav" class="back">Back</a>
            <h1 id="list-title">title</h1>
        </div>
        <div id="navigation-content">
            <?php echo $this->modules('main.mobile.list') ?>
        </div>
    </div>
    <div id="instance-list">
        <div class="toolbar">
            <a href="#nav" class="back">Back</a>
            <h1 id="instance-title">title</h1>
        </div>
        <div id="instance-content">
            <!-- stuff here -->
        </div>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
