<?php echo $this->doctype('XHTML1_STRICT') ?>
<html>
<head>
    <title>OntoWiki</title>

    <?php if ($this->has('jsonVars')): ?>
        <script type="text/javascript">
            <?php echo $this->jsonVars ?>
        </script>
    <?php endif; ?>

    <!-- stylesheets -->
    <style type="text/css" media="screen">@import "extensions/themes/mobile/jqtouch/jqtouch.min.css";</style>
    <style type="text/css" media="screen">@import "extensions/themes/mobile/jqt/theme.min.css";</style>
    <style type="text/css" media="screen">
        .hasMenu {
            color: #ffffff;
            font-weight: bold;
        }
        li span {
            font-weight: normal;
            font-size: 18px;
            color: #FFFFFF;
        }
        span ol li {
            font-weight: normal;
            font-size: 18px;
            color: #FFFFFF;
        }
        .pager{
            background: #4c4d4e;
            border: 1px solid #333;
            font-size: 18px;
            text-align: center;
            width: 12.5%;
            float: left;
            -webkit-border-radius: 8px;
            -webkit-box-sizing: border-box;
            display: block;
            margin-right: 5px;
            padding: 11px 10px 14px 10px;
            -webkit-box-shadow: rgba(0,0,0,.2) 1px 1px 3px;
            background: -webkit-gradient(linear, 0% 0%, 0% 100%, from(#4c4d4e), to(#404142));
        }
        .pager a{
            color: #FFFFFF;
            font-weight: bold;
            text-decoration: none;
        }
        .pager a.selected{
            color: #3e9ac3;
            font-weight: bold;
            text-decoration: none;
        }
        .pager a.disabled{
            color: #666666;
            font-weight: bold;
            text-decoration: none;
        }
    </style>

    <!-- jQTouch -->
    <script type="text/javascript" src="extensions/themes/mobile/jqtouch/jquery.1.3.2.min.js" charset="utf-8"></script>
    <script type="application/x-javascript" src="extensions/themes/mobile/jqtouch/jqtouch.js" charset="utf-8"></script>

    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.livequery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.json.js"></script>

    <!-- <script type="text/javascript" src="http://localhost/ontowiki/extensions/components/datagathering/scripts/jquery.autocomplete.js"></script>
    <script type="text/javascript" src="http://localhost/ontowiki/extensions/components/datagathering/datagathering.js"></script> -->
    <script type="text/javascript" src="extensions/modules/modellist/modellist.js"></script>
    <script type="text/javascript" src="extensions/modules/navigation/navigation.js"></script>

    <script type="text/javascript" charset="utf-8" src="extensions/themes/mobile/base.js"></script>
</head>
<body>
    <div id="home">
        <div class="toolbar">
            <!-- <a href="#innercontent" class="button leftButton flip">Login</a> -->
            <h1>OntoWiki Mobile</h1>
        </div>
        <?php echo $this->modules('main.mobile.baselist') ?>
    </div>
    <div id="nav">
        <div class="toolbar">
            <a href="#" class="back">Back</a>
            <h1 id="nav-title">title</h1>
            <a href="#" class="button" onclick="toggleMenu(this);">Menu</a>
        </div>
        <?php echo $this->modules('main.mobile.navigation') ?>
    </div>
    <div id="list">
        <div class="toolbar">
            <a href="#nav" class="back">Back</a>
            <h1 id="list-title">title</h1>
            <a href="#" class="button" onclick="toggleMenu(this);">Menu</a>
        </div>
        <div id="navigation-content">
            <?php echo $this->modules('main.mobile.list') ?>
        </div>
    </div>
    <div id="instance-list">
        <div class="toolbar">
            <a href="#list" class="back">Back</a>
            <h1 id="instance-title">title</h1>
            <a href="#" class="button" onclick="toggleMenu(this);">Menu</a>
        </div>
        <div id="instance-content">
            <!-- stuff here -->
        </div>
    </div>
    <div id="properties-list">
        <div class="toolbar">
            <a href="#instance-list" class="back">Back</a>
            <h1 id="properties-title">title</h1>
            <a href="#" class="button" onclick="toggleMenu(this);">Menu</a>
        </div>
        <div id="properties-content">
            <!-- stuff here -->
        </div>
    </div>
    <div id="searchres-list">
        <div class="toolbar">
            <a href="#" class="back">Back</a>
            <h1 id="searchres-title">title</h1>
        </div>
        <div id="searchres-content">
            <!-- stuff here -->
        </div>
    </div>
    <?php echo $this->inlineScript() ?>
</body>
</html>
