<?php /* you can use $this->has() as a shortcut */ ?>
<?php if (isset($this->description['http://purl.org/dc/elements/1.1/description'])) : ?>
<p>
    <?php echo $this->description['http://purl.org/dc/elements/1.1/description'][0]['value']; ?>
</p>
<?php elseif (isset($this->description['http://rdfs.org/sioc/ns#content'])) : ?>
<p>
    <?php echo $this->description['http://rdfs.org/sioc/ns#content'][0]['value']; ?>
</p>
<?php endif ?>
