<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN" "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en"
    xmlns:dc="http://purl.org/dc/terms/"
    xmlns:foaf="http://xmlns.com/foaf/0.1/">
<head>
    <meta name="generator" content="<?php echo $this->generator ?>" />
    <link rel="alternate" type="application/rdf+xml" href="<?php echo $this->resourceUri ?>.rdf" />
    <link rel="pingback" href="<?php echo $this->pingbackUri ?>" />

    <link
        rel="<?php echo $this->curie('http://xmlns.com/foaf/0.1/primaryTopic') ?>"
        href="<?php echo $this->resourceUri?>" />

    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/main.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/reset.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/text.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/grid.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/layout.css" media="screen" />
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/nav.css" media="screen" />
    <!--[if IE 6]><link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/ie6.css" media="screen" /><![endif]-->
    <!--[if IE 7]><link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/ie.css" media="screen" /><![endif]-->

    <script type="text/javascript" src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAceda6Yw6e6J-g107iwZV7hTIeIURPFxrextC5MRl2maca5MTzhTNeVDyWhGWLe9g4SymA-sNcLmZjA"></script>
    <!-- jQuery -->
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery.js"></script>
    <script type="text/javascript" src="<?php echo $this->themeUrlBase ?>scripts/libraries/jquery-ui.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.calculation.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery.gmap-1.1.0-min.js"></script>
    <!--script type="text/javascript" src="<?php echo $this->baseUri ?>/js/jquery-fluid16.js"></script-->
    <script type="text/javascript" src="<?php echo $this->baseUri ?>/js/spiders.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUri ?>/css/spiders.css" media="screen" />

    <title><?php echo $this->descriptionHelper->getTitle($this->resourceUri) ?> :: Caucasian Spiders</title>
</head>
<body about="<?php echo $this->resourceUri?>">
<?php
    // this is the standard template data
    $templateData = array(
                    'title' => $this->descriptionHelper->getTitle($this->resourceUri),
                    'resourceUri' => $this->resourceUri,
                    'description' => $this->description[$this->resourceUri],
                    'descriptionHelper' => $this->descriptionHelper
            );
    function printNavi($navi, $titleHelper, $depth){
        if(is_array($navi) && count($navi)>0):?>
                    <?php foreach ($navi as $navurl => $subnavi) : ?>
                    <li>
                        <a href="<?php echo $navurl ?>"><?php for($i=0; $i< $depth; $i++){echo "&nbsp;&nbsp;";} echo $titleHelper->getTitle($navurl) ?></a>
                        <?php printNavi($subnavi, $titleHelper, $depth+1); ?>
                    </li>
                    <?php endforeach; ?>
       <?php endif; 
   }

?>
<div class="container_16">
    <div class="grid_16">
        <h1 id="branding">
            <a href="<?php echo $this->site['index'] ?>"><?php echo $this->site['name'] ?></a>
        </h1>
    </div>
    <div class="clear"></div>
    <div class="grid_16">
        <ul class="nav main">
            <li><a href="http://db.caucasus-spiders.info/Document/Checklists.html">Home</a></li>
            <li><a href="http://db.caucasus-spiders.info/Area/152">Checklists: Caucasus</a>
                <ul>
                    <li><a href="http://db.caucasus-spiders.info/Area/100">Georgia</a></li>
                    <li><a href="http://db.caucasus-spiders.info/Area/4">Azerbaijan</a></li>
                    <li><a href="http://db.caucasus-spiders.info/Area/95">Armenia</a></li>
                    <li><a href="http://db.caucasus-spiders.info/Area/865">North Caucasus</a></li>
                </ul>
            </li>
            <li><a href="http://caucasus-spiders.info/introduction/checklists/bibliography-2/">Literature</a></li>
            <li><a href="http://caucasus-spiders.info/spider-habitats/">Spider Habitats</a></li>
            <li><a href="http://caucasus-spiders.info/faq/">FAQ</a></li>

            <li class="secondary">
                <a href="<?php echo $this->wikiBaseUri ?>view?r=<?php echo $this->resourceUri ?>">OntoWiki</a>
            </li>
        </ul>

    </div>
    <div class="clear"></div>
    <div class="grid_16">
        <h2 id="page-heading"></h2>
    </div>

    <div class="grid_11">
        <?php echo $this->partial('spiders/main.phtml', $templateData) ?>
        <?php echo $this->partial('spiders/feed.phtml', $templateData) ?>
        <div class="clear"></div>
    </div>

    <div class="grid_5">
        <div class="box">
            <h2>Last Changes</h2>
            <?php echo $this->module('lastchanges', new Zend_Config(array('noChrome' => true))); ?>
        </div>
    </div>

    <div class="grid_16" id="site_info">
        <div class="box">
            <p>This page is proudly powered by
                <a href="http://ontowiki.net" title="OntoWiki is a Semantic Data Wiki enabling the collaborative creation and (linked data) publication of RDF knowledge bases."><?php echo $this->generator ?></a>,
                <a href="http://www.designinfluences.com/fluid960gs/" title="The 960 Grid System is an effort to streamline web development workflow by providing commonly used dimensions, based on a width of 960 pixels.">Fluid 960 Grid System</a> and
                <a href="jquery.com" title="jQuery is a fast and concise JavaScript Library that simplifies HTML document traversing, event handling, animating, and Ajax interactions for rapid web development.">jQuery</a>.

        </div>
    </div>
    <div class="clear"></div>
</div>

<!-- Google Analytics -->
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-241023-11']);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<!-- Google Analytics end -->
</body>
</html>
