<?php
$ow = OntoWiki::getInstance();
$this->headScript()->appendFile($ow->extensionManager->getComponentUrl('exconf')."resources/jquery.togglebutton.js");
$this->headLink()->appendStylesheet($ow->extensionManager->getComponentUrl('exconf')."resources/togglebutton.css");
$this->headScript()->appendScript('$(function(){
    function postToggle(button){
            var name = $(button).parent().attr("id");
            var enabled = $(button).attr("selected");
            $.post(urlBase + "exconf/conf/?name="+name+"&enabled="+enabled,function(data){if(data==""){$("#numEnabled").html(parseInt($("#numEnabled").html())+( enabled == "true" ? 1 : -1));$("#numDisabled").html(parseInt($("#numDisabled").html())+( enabled == "true" ? -1 : 1));}});
        }
 $(".togglebutton").togglebutton(
    {"onEnable":
        postToggle,
     "onDisable":
        postToggle
    }
 );

    $("#show_extension input:radio").change(function()
    {
       switch($("#show_extension input:checked").val()){
             case "all" :
                $("#extensions tr").each(function(){
                    $(this).show();
                })
             break;
             case "enabled" :
                $("#extensions tr").each(function(){if($(this).find(".togglebutton").attr("selected") == "true"){
                    $(this).show();
                } else {
                    $(this).hide();
                }})
             break;
             case "disabled" :
                $("#extensions tr").each(function(){if($(this).find(".togglebutton").attr("selected") == "true"){
                    $(this).hide();
                } else {
                    $(this).show();
                }})
             break;
         }

         // re-populate the outline
         extensionOutline();

         //fix odd even style
         var even = true;
         $("#extensions tr:visible").each(function(){
            if(even){
               $(this).addClass("even").removeClass("odd");
            } else {
                $(this).addClass("odd").removeClass("even");
            }
            even = !even;
         })
    }
    );
 });

');
?>
Show
<form id="show_extension">
    <input type="radio" name="show" value="all" checked> All (<span id="numAll"><?php echo $this->numAll; ?></span>)<br/>
    <input type="radio" name="show" value="enabled"> Enabled (<span id="numEnabled"><?php echo $this->numEnabled; ?></span>)<br/>
    <input type="radio" name="show" value="disabled"> Disabled (<span id="numDisabled"><?php echo $this->numDisabled; ?></span>)
</form>
<hr class="horizontal"/>
<table id="extensions">
<?php $odd = false; foreach($this->extensions as $name => $extension){ ?>
    <tr class="<?php echo $odd ? "odd" : "even"; ?>">
        <td>
            <div class="extension has-contextmenu-area" id="<?php echo $name; ?>">
                <div class="name"><h3><?php echo isset($extension->name) ? $extension->name : $name; ?></h3></div>
                <div class="description"><?php echo isset($extension->description) ? $extension->description : "no description yet"; ?></div>
                <div class="author">
                    <?php if(isset($extension->authorUrl)) { ?><a href="<?php echo $extension->authorUrl;?>"><?php } ?>
                    <?php echo isset($extension->author) ? $extension->author : "author unknown"; ?>
                    <?php if(isset($extension->authorUrl)) { ?></a><?php } ?>
                </div>
                <div class="togglebutton" <?php if(isset($extension->enabled) && $extension->enabled){ echo "selected=\"true\""; } ?>></div>
                <div class="contextmenu">
                <?php if(isset($extension->homepage)) : ?>
                    <a href="<?php echo $extension->homepage ?>" class="item">
                        <span title="Go to plugin homepage" class="icon icon-homepage">
                            <span>Go to plugin homepage</span>
                        </span>
                    </a>
                <?php endif; ?>
                    <a href="<?php echo $this->urlBase; ?>exconf/conf/?name=<?php echo $name; ?>" class="item">
                        <span title="Configure" class="icon icon-edit">
                            <span>Configure</span>
                        </span>
                    </a>
                    <a href="<?php echo $this->urlBase; ?>exconf/conf/?name=<?php echo $name; ?>&remove=1" class="item">
                        <span title="Remove permanently" class="icon icon-delete">
                            <span>Remove permanently</span>
                        </span>
                    </a>
                </div>
            </div>
        </td>
    </tr>
<?php 
$odd = !$odd; 
} 
?>
</table>
       